package plugins

// sssd.go — Sprint 36 Day 3
//
// SSSDPlugin renders /etc/sssd/sssd.conf for the node identified by
// state.NodeID. The file is fully owned by clustr (no anchors); the
// rendered output is byte-identical to what the imperative finalization
// path produces via deploy.renderSSSDConf.

import (
	"fmt"
	"strings"

	"github.com/sqoia-dev/clustr/internal/config"
	"github.com/sqoia-dev/clustr/pkg/api"
)

// sssdWatchKey is the config-tree path the SSSD plugin subscribes to.
//
// LDAPConfig is a structured sub-object on NodeConfig; it is updated by the
// LDAP module (POST /api/v1/modules/ldap/enable and related routes), not by
// the generic UpdateNode PUT. The observer receives a Notify call with this
// key whenever the LDAP module writes new bind credentials or CA cert.
const sssdWatchKey = "nodes.*.ldap_config"

// SSSDPlugin renders /etc/sssd/sssd.conf for the node identified by
// state.NodeID. It is stateless and safe for concurrent invocation.
//
// Render contract:
//   - Pure and idempotent: same NodeID + same LDAPConfig → same output.
//   - No anchors: /etc/sssd/sssd.conf is single-purpose and fully managed by
//     clustr. A full overwrite is safe.
//   - Returns a nil slice when LDAPConfig is nil, so the observer does not
//     fire a push for nodes where LDAP is not enabled.
//
// Registration: call config.Register(SSSDPlugin{}) once at startup inside the
// reactiveConfigPluginsOnce.Do block.
type SSSDPlugin struct{}

// Name returns the stable plugin identifier used in DB rows and WS messages.
func (SSSDPlugin) Name() string { return "sssd" }

// WatchedKeys returns the config-tree path this plugin subscribes to.
// The observer indexes this key verbatim; the LDAP module must emit the same
// literal string via config.Notify when LDAPConfig changes.
func (SSSDPlugin) WatchedKeys() []string {
	return []string{sssdWatchKey}
}

// SSSDWatchKey returns the literal watch-key string so callers (server wiring,
// tests) can reference it without importing the unexported constant.
func SSSDWatchKey() string { return sssdWatchKey }

// Metadata returns the execution and safety invariants for the SSSD plugin.
//
// Priority 80: must run after hostname/hosts (Foundation band) but before any
// slurm config that references LDAP-resolved users. Sits in the Middleware
// band (51–100).
//
// Dangerous=true (Sprint 41 Day 3): a misrendered sssd.conf breaks login for all
// LDAP-resolved users. On a lab where every operator is LDAP-backed this is
// lockout-class. Operators must supply the typed cluster name via the
// POST /api/v1/config/dangerous-push → confirm handshake before delivery.
// The confirmation gate is feature-flagged behind CLUSTR_DANGEROUS_GATE_ENABLED=1;
// when the flag is off the regular push path operates as before (no gate).
//
// Backup=nil on Day 3; wired in Sprint 41 Day 4.
func (SSSDPlugin) Metadata() config.PluginMetadata {
	return config.PluginMetadata{
		Priority:     80,
		Dangerous:    true,
		DangerReason: "SSSD restart can sever active operator SSH sessions if PAM stack is broken; a misrendered sssd.conf breaks login for all LDAP users and requires console access to recover",
	}
}

// Render returns a single InstallInstruction that writes /etc/sssd/sssd.conf
// for the node identified by state.NodeID.
//
// Returns nil, nil when state.NodeConfig.LDAPConfig is nil — the observer
// treats a nil slice as "nothing to push" and skips the WS send.
func (SSSDPlugin) Render(state config.ClusterState) ([]api.InstallInstruction, error) {
	ldapCfg := state.NodeConfig.LDAPConfig
	if ldapCfg == nil {
		return nil, nil
	}
	if ldapCfg.BaseDN == "" {
		return nil, fmt.Errorf("sssd plugin: LDAPConfig.BaseDN is empty")
	}

	domain := ldapDomainFromBaseDN(ldapCfg.BaseDN)
	content := renderSSSDConf(ldapCfg, domain)

	instr := api.InstallInstruction{
		Opcode:  "overwrite",
		Target:  "/etc/sssd/sssd.conf",
		Payload: content,
		// No Anchors: /etc/sssd/sssd.conf is a single-purpose file fully
		// owned by this plugin. A full overwrite is correct and idempotent.
	}

	return []api.InstallInstruction{instr}, nil
}

// renderSSSDConf renders the sssd.conf content for a node. The output is
// byte-identical to the output of deploy.renderSSSDConf in
// internal/deploy/finalize.go — this is the reactive-config equivalent.
//
// The function is duplicated here rather than imported from the deploy package
// to avoid creating a cyclic import (deploy → config → deploy). The deploy
// package is a leaf package; config must not import it.
func renderSSSDConf(cfg *api.LDAPNodeConfig, domain string) string {
	return fmt.Sprintf(`# sssd.conf — generated by clustr-serverd
# DO NOT EDIT — managed by clustr. Regenerated on each reimage.

[sssd]
services = nss, pam, ssh
domains = %s

[nss]
homedir_substring = /home

[pam]
offline_credentials_expiration = 7

[domain/%s]
id_provider = ldap
auth_provider = ldap
chpass_provider = ldap
access_provider = ldap

ldap_uri = %s
ldap_search_base = %s

ldap_default_bind_dn = %s
ldap_default_authtok_type = password
ldap_default_authtok = %s

ldap_user_object_class = posixAccount
ldap_user_search_base = ou=people,%s
ldap_user_name = uid
ldap_user_uid_number = uidNumber
ldap_user_gid_number = gidNumber
ldap_user_home_directory = homeDirectory
ldap_user_shell = loginShell
ldap_user_gecos = gecos
ldap_user_shadow_expire = shadowExpire

ldap_group_object_class = posixGroup
ldap_group_search_base = ou=groups,%s
ldap_group_name = cn
ldap_group_gid_number = gidNumber
ldap_group_member = memberUid

ldap_tls_reqcert = allow
ldap_tls_cacert = /etc/pki/ca-trust/source/anchors/clustr-ca.crt

ldap_account_expire_policy = shadow
ldap_access_order = ppolicy, expire
ldap_use_ppolicy = true
ldap_pwd_policy = none

ldap_id_use_start_tls = false
ldap_referrals = false
enumerate = false
cache_credentials = true
entry_cache_timeout = 300
`, domain, domain,
		cfg.ServerURI, cfg.BaseDN,
		cfg.ServiceBindDN, cfg.ServiceBindPasswd,
		cfg.BaseDN, cfg.BaseDN)
}

// ldapDomainFromBaseDN extracts the first DC component from a base DN.
// "dc=cluster,dc=local" → "cluster"
// Duplicated from internal/deploy/finalize.go for the same cycle-avoidance
// reason as renderSSSDConf above.
func ldapDomainFromBaseDN(baseDN string) string {
	parts := strings.SplitN(baseDN, ",", 2)
	if len(parts) == 0 {
		return baseDN
	}
	first := strings.TrimSpace(parts[0])
	if after, ok := strings.CutPrefix(first, "dc="); ok {
		return after
	}
	return first
}
