// configgen_test.go — golden-file tests for switch config template rendering (S1-5, TD-1).
// Tests cover five vendor/scenario pairs using RenderSwitchTemplate (pure function, no DB).
package network

import (
	"strings"
	"testing"
)

// ─── Fixture helpers ──────────────────────────────────────────────────────────

func accessOnlyData(switchName string) SwitchConfigData {
	return SwitchConfigData{
		SwitchName: switchName,
		Role:       "leaf",
		VLANs: []VLANConfig{
			{ID: 10, Name: "compute", Description: "compute VLAN"},
			{ID: 20, Name: "management", Description: "mgmt VLAN"},
		},
		ServerPorts: []PortConfig{
			{Name: "Ethernet1", Description: "node01 eth0", VLANID: 10, Mode: "access"},
			{Name: "Ethernet2", Description: "node02 eth0", VLANID: 10, Mode: "access"},
		},
		UplinkPorts: []PortConfig{
			{Name: "Ethernet48", Description: "uplink to spine", Mode: "trunk"},
		},
		MTU: 9000,
	}
}

func withLAG(data SwitchConfigData) SwitchConfigData {
	data.LAGs = []LAGConfig{
		{
			ID:          1,
			Description: "node01 dual NIC bond",
			MemberPorts: []string{"Ethernet1", "Ethernet2"},
			Mode:        "lacp",
		},
	}
	return data
}

func withPFC(data SwitchConfigData) SwitchConfigData {
	data.EnablePFC = true
	data.PFCPriority = 3
	return data
}

// ─── Arista golden tests ──────────────────────────────────────────────────────

func TestRenderSwitchTemplate_Arista_AccessPorts(t *testing.T) {
	data := accessOnlyData("spine-01")
	out, err := RenderSwitchTemplate("arista", data)
	if err != nil {
		t.Fatalf("render arista: %v", err)
	}

	mustContain(t, out, "! Arista EOS configuration generated by clustr")
	mustContain(t, out, "Switch: spine-01")
	mustContain(t, out, "vlan 10")
	mustContain(t, out, "vlan 20")
	mustContain(t, out, "interface Ethernet1")
	mustContain(t, out, "switchport mode access")
	mustContain(t, out, "switchport access vlan 10")
	mustContain(t, out, "interface Ethernet48")
	mustContain(t, out, "switchport mode trunk")
	mustNotContain(t, out, "priority-flow-control") // PFC not requested
}

func TestRenderSwitchTemplate_Arista_WithPFC(t *testing.T) {
	data := withPFC(accessOnlyData("data-leaf-01"))
	out, err := RenderSwitchTemplate("arista", data)
	if err != nil {
		t.Fatalf("render arista+pfc: %v", err)
	}

	mustContain(t, out, "priority-flow-control mode on")
	mustContain(t, out, "priority-flow-control priority 3 no-drop")
	mustContain(t, out, "dcbx mode ieee")
}

func TestRenderSwitchTemplate_Arista_WithLAG(t *testing.T) {
	data := withLAG(accessOnlyData("leaf-02"))
	out, err := RenderSwitchTemplate("arista", data)
	if err != nil {
		t.Fatalf("render arista+lag: %v", err)
	}

	mustContain(t, out, "interface Port-Channel1")
	mustContain(t, out, "port-channel lacp fallback static")
	mustContain(t, out, "interface Ethernet1")
	mustContain(t, out, "channel-group")
	mustContain(t, out, "mode active") // lacp → active
}

// ─── Juniper golden tests ─────────────────────────────────────────────────────

func TestRenderSwitchTemplate_Juniper_Basic(t *testing.T) {
	data := accessOnlyData("qfx-01")
	out, err := RenderSwitchTemplate("juniper", data)
	if err != nil {
		t.Fatalf("render juniper: %v", err)
	}

	// Juniper template should reference switch name.
	mustContain(t, out, "qfx-01")
	// VLANs should appear.
	mustContain(t, out, "10")
	mustContain(t, out, "compute")
	// Should not be empty.
	if len(strings.TrimSpace(out)) < 50 {
		t.Errorf("juniper output too short (%d bytes), likely template failure", len(out))
	}
}

// ─── Generic fallback golden tests ───────────────────────────────────────────

func TestRenderSwitchTemplate_Generic_FallbackForUnknownVendor(t *testing.T) {
	data := accessOnlyData("mystery-switch")
	out, err := RenderSwitchTemplate("brocade", data) // unknown → generic
	if err != nil {
		t.Fatalf("render generic via unknown vendor: %v", err)
	}

	mustContain(t, out, "Generic switch configuration plan")
	mustContain(t, out, "mystery-switch")
	mustContain(t, out, "compute VLAN")
}

func TestRenderSwitchTemplate_Generic_EmptyVendor(t *testing.T) {
	data := accessOnlyData("no-vendor-switch")
	out, err := RenderSwitchTemplate("", data)
	if err != nil {
		t.Fatalf("render generic via empty vendor: %v", err)
	}
	mustContain(t, out, "Generic switch configuration plan")
}

// ─── Default MTU injection ────────────────────────────────────────────────────

func TestRenderSwitchTemplate_DefaultMTU(t *testing.T) {
	data := accessOnlyData("mtu-switch")
	data.MTU = 0 // force default
	out, err := RenderSwitchTemplate("arista", data)
	if err != nil {
		t.Fatalf("render with zero MTU: %v", err)
	}
	// Default MTU 9000 should be injected automatically.
	mustContain(t, out, "9000")
}

// ─── Trunk port mode ─────────────────────────────────────────────────────────

func TestRenderSwitchTemplate_Arista_TrunkPort(t *testing.T) {
	data := SwitchConfigData{
		SwitchName: "trunk-switch",
		Role:       "leaf",
		VLANs:      []VLANConfig{{ID: 100, Name: "bond"}},
		ServerPorts: []PortConfig{
			{Name: "Ethernet10", Description: "bonded server", VLANID: 100, Mode: "trunk"},
		},
		MTU: 9000,
	}
	out, err := RenderSwitchTemplate("arista", data)
	if err != nil {
		t.Fatalf("render trunk port: %v", err)
	}
	mustContain(t, out, "switchport mode trunk")
	mustContain(t, out, "switchport trunk allowed vlan 100")
}

// ─── helpers ─────────────────────────────────────────────────────────────────

func mustContain(t *testing.T, s, sub string) {
	t.Helper()
	if !strings.Contains(s, sub) {
		t.Errorf("output does not contain %q\nFull output:\n%s", sub, s)
	}
}

func mustNotContain(t *testing.T, s, sub string) {
	t.Helper()
	if strings.Contains(s, sub) {
		t.Errorf("output should not contain %q but does\nFull output:\n%s", sub, s)
	}
}
