package deploy

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/sqoia-dev/clonr/pkg/api"
	"github.com/sqoia-dev/clonr/pkg/ipmi"
)

// ifaceNameRe validates that a network interface name contains only safe
// characters before it is used to construct a filename.
var ifaceNameRe = regexp.MustCompile(`^[a-zA-Z0-9._:-]+$`)

// mdRaidArraysRules is the content of the 63-md-raid-arrays.rules udev rule
// file. It is embedded directly so it can be injected into the deployed OS
// chroot even when the deploy host (PXE initramfs) does not have it installed.
// This rule causes udev to create /dev/disk/by-id/md-uuid-* and
// /dev/disk/by-id/md-name-* symlinks when md arrays become active, which
// dracut's initqueue finished-hooks depend on to declare the root device ready.
const mdRaidArraysRules = `# do not edit this file, it will be overwritten on update

SUBSYSTEM!="block", GOTO="md_end"

# handle md arrays
ACTION=="remove", GOTO="md_end"
KERNEL!="md*", GOTO="md_end"

# partitions have no md/{array_state,metadata_version}, but should not
# for that reason be ignored.
ENV{DEVTYPE}=="partition", GOTO="md_ignore_state"

# container devices have a metadata version of e.g. 'external:ddf' and
# never leave state 'inactive'
ATTR{md/metadata_version}=="external:[A-Za-z]*", ATTR{md/array_state}=="inactive", GOTO="md_ignore_state"
TEST!="md/array_state", ENV{SYSTEMD_READY}="0", GOTO="md_end"
ATTR{md/array_state}=="clear*|inactive", ENV{SYSTEMD_READY}="0", GOTO="md_end"
ATTR{md/sync_action}=="reshape", ENV{RESHAPE_ACTIVE}="yes"
LABEL="md_ignore_state"

IMPORT{program}="/usr/sbin/mdadm --detail --no-devices --export $devnode"
ENV{DEVTYPE}=="disk", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}", OPTIONS+="string_escape=replace"
ENV{DEVTYPE}=="disk", ENV{MD_UUID}=="?*", SYMLINK+="disk/by-id/md-uuid-$env{MD_UUID}"
ENV{DEVTYPE}=="disk", ENV{MD_DEVNAME}=="?*", SYMLINK+="md/$env{MD_DEVNAME}"
ENV{DEVTYPE}=="partition", ENV{MD_NAME}=="?*", SYMLINK+="disk/by-id/md-name-$env{MD_NAME}-part%n", OPTIONS+="string_escape=replace"
ENV{DEVTYPE}=="partition", ENV{MD_UUID}=="?*", SYMLINK+="disk/by-id/md-uuid-$env{MD_UUID}-part%n"
ENV{DEVTYPE}=="partition", ENV{MD_DEVNAME}=="*[^0-9]", SYMLINK+="md/$env{MD_DEVNAME}%n"
ENV{DEVTYPE}=="partition", ENV{MD_DEVNAME}=="*[0-9]", SYMLINK+="md/$env{MD_DEVNAME}p%n"

IMPORT{builtin}="blkid"
OPTIONS+="link_priority=100"
OPTIONS+="watch"
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_UUID_ENC}=="?*", SYMLINK+="disk/by-uuid/$env{ID_FS_UUID_ENC}"
ENV{ID_FS_USAGE}=="filesystem|other", ENV{ID_PART_ENTRY_UUID}=="?*", SYMLINK+="disk/by-partuuid/$env{ID_PART_ENTRY_UUID}"
ENV{ID_FS_USAGE}=="filesystem|other", ENV{ID_FS_LABEL_ENC}=="?*", SYMLINK+="disk/by-label/$env{ID_FS_LABEL_ENC}"

ENV{MD_LEVEL}=="raid[1-9]*", ENV{SYSTEMD_WANTS}+="mdmonitor.service"

# Tell systemd to run mdmon for our container, if we need it.
ENV{MD_LEVEL}=="raid[1-9]*", ENV{MD_CONTAINER}=="?*", PROGRAM="/usr/bin/readlink $env{MD_CONTAINER}", ENV{MD_MON_THIS}="%c"
ENV{MD_MON_THIS}=="?*", TEST=="/etc/initrd-release", PROGRAM="/usr/bin/basename $env{MD_MON_THIS}", ENV{SYSTEMD_WANTS}+="mdmon@initrd-%c.service"
ENV{MD_MON_THIS}=="?*", TEST!="/etc/initrd-release", PROGRAM="/usr/bin/basename $env{MD_MON_THIS}", ENV{SYSTEMD_WANTS}+="mdmon@%c.service"
ENV{RESHAPE_ACTIVE}=="yes", PROGRAM="/usr/bin/basename $env{MD_MON_THIS}", ENV{SYSTEMD_WANTS}+="mdadm-grow-continue@%c.service"

LABEL="md_end"
`

// mdRaidAssemblyRules is the content of the 64-md-raid-assembly.rules udev
// rule file. It handles incremental RAID assembly (adding member devices one
// by one as they appear). Embedded directly for the same reason as
// mdRaidArraysRules above.
const mdRaidAssemblyRules = `# do not edit this file, it will be overwritten on update

# Don't process any events if anaconda is running as anaconda brings up
# raid devices manually
ENV{ANACONDA}=="?*", GOTO="md_inc_end"
# assemble md arrays

SUBSYSTEM!="block", GOTO="md_inc_end"

# skip non-initialized devices
ENV{SYSTEMD_READY}=="0", GOTO="md_inc_end"

# handle potential components of arrays (the ones supported by md)
# For member devices which are md/dm devices, we don't need to
# handle add event. Because md/dm devices need to do some init jobs.
# Then the change event happens.
# When adding md/dm devices, ID_FS_TYPE can only be linux_raid_member
# after change event happens.
ENV{ID_FS_TYPE}=="linux_raid_member", GOTO="md_inc"

# "noiswmd" on kernel command line stops mdadm from handling
#  "isw" (aka IMSM - Intel RAID).
# "nodmraid" on kernel command line stops mdadm from handling
#  "isw" or "ddf".
IMPORT{cmdline}="noiswmd"
IMPORT{cmdline}="nodmraid"

ENV{nodmraid}=="?*", GOTO="md_inc_end"
ENV{ID_FS_TYPE}=="ddf_raid_member", GOTO="md_inc"
ENV{noiswmd}=="?*", GOTO="md_inc_end"
ENV{ID_FS_TYPE}=="isw_raid_member", ACTION!="change", GOTO="md_inc"
GOTO="md_inc_end"

LABEL="md_inc"

# Bare disks are ready when add event happens, the raid can be assembled.
ACTION=="change", KERNEL!="dm-*|md*", GOTO="md_inc_end"

# remember you can limit what gets auto/incrementally assembled by
# mdadm.conf(5)'s 'AUTO' and selectively whitelist using 'ARRAY'
ACTION!="remove", IMPORT{program}="/usr/sbin/mdadm --incremental --export $devnode --offroot $env{DEVLINKS}"
ACTION!="remove", ENV{MD_STARTED}=="*unsafe*", ENV{MD_FOREIGN}=="no", ENV{SYSTEMD_WANTS}+="mdadm-last-resort@$env{MD_DEVICE}.timer"

ACTION=="remove", ENV{ID_PATH}=="?*", RUN+="/usr/sbin/mdadm -If $devnode --path $env{ID_PATH}"
ACTION=="remove", ENV{ID_PATH}!="?*", RUN+="/usr/sbin/mdadm -If $devnode"

LABEL="md_inc_end"
`

// applyNodeConfig writes all node-specific identity into the deployed filesystem
// rooted at mountRoot. This function is called by both FilesystemDeployer and
// BlockDeployer after the image is on disk.
//
// Order of operations:
//  1. Hostname
//  2. Network config (NetworkManager keyfiles)
//  3. SSH authorized_keys for root
//  4. /etc/fstab UUID update
//  5. Kernel args (GRUB)
//  6. BMC / IPMI network and credentials (if cfg.BMC is set)
//  7. InfiniBand / IPoIB config (if cfg.IBConfig is set)
func applyNodeConfig(ctx context.Context, cfg api.NodeConfig, mountRoot string) error {
	log := logger()

	log.Info().Str("hostname", cfg.Hostname).Msg("finalize: writing /etc/hostname")
	if err := writeHostname(mountRoot, cfg.Hostname, cfg.FQDN); err != nil {
		return fmt.Errorf("finalize: hostname: %w", err)
	}
	log.Info().Str("hostname", cfg.Hostname).Msg("finalize: wrote /etc/hostname")

	log.Info().Int("interfaces", len(cfg.Interfaces)).Msg("finalize: writing NetworkManager connection profiles")
	if err := writeNetworkConfig(mountRoot, cfg.Interfaces); err != nil {
		return fmt.Errorf("finalize: network: %w", err)
	}
	for _, iface := range cfg.Interfaces {
		log.Info().Str("interface", iface.Name).Str("ip", iface.IPAddress).
			Msgf("finalize: wrote /etc/NetworkManager/system-connections/%s.nmconnection", iface.Name)
	}

	if len(cfg.SSHKeys) > 0 {
		log.Info().Int("keys", len(cfg.SSHKeys)).Msg("finalize: writing /root/.ssh/authorized_keys")
		if err := writeSSHKeys(mountRoot, cfg.SSHKeys); err != nil {
			return fmt.Errorf("finalize: ssh keys: %w", err)
		}
		log.Info().Int("keys", len(cfg.SSHKeys)).Msg("finalize: wrote /root/.ssh/authorized_keys")
	}

	if cfg.KernelArgs != "" {
		log.Info().Str("args", cfg.KernelArgs).Msg("finalize: applying kernel args to /etc/default/grub")
		if err := applyKernelArgs(ctx, mountRoot, cfg.KernelArgs); err != nil {
			// Non-fatal: the GRUB config file edit may have succeeded even if
			// grub2-mkconfig failed in the chroot. Log prominently so operators
			// know to verify the bootloader configuration manually.
			log.Warn().Err(err).Msg("WARNING: finalize: kernel args update failed (non-fatal) — manual intervention may be required")
		} else {
			log.Info().Str("args", cfg.KernelArgs).Msg("finalize: kernel args applied, ran grub2-mkconfig")
		}
	}

	// BMC / IPMI — configure local BMC network and credentials.
	// This operates on the physical BMC directly (not the chroot), so it is
	// done here rather than inside the deployed filesystem.
	if cfg.BMC != nil {
		log.Info().Str("bmc_ip", cfg.BMC.IPAddress).Msg("finalize: configuring BMC via ipmitool")
		if err := applyBMCConfig(ctx, cfg.BMC); err != nil {
			// Non-fatal: BMC configuration failure should not abort a deployment.
			// The operator can manually configure the BMC afterward.
			log.Warn().Err(err).Msg("WARNING: finalize: BMC configuration failed (non-fatal)")
		} else {
			log.Info().Str("bmc_ip", cfg.BMC.IPAddress).Msg("finalize: BMC configured")
		}
	}

	// InfiniBand / IPoIB — write udev rules and NetworkManager profiles into
	// the deployed filesystem so IB interfaces come up correctly on first boot.
	if len(cfg.IBConfig) > 0 {
		log.Info().Int("devices", len(cfg.IBConfig)).Msg("finalize: writing InfiniBand/IPoIB configuration")
		if err := writeIBConfig(mountRoot, cfg.IBConfig); err != nil {
			return fmt.Errorf("finalize: ib config: %w", err)
		}
		log.Info().Int("devices", len(cfg.IBConfig)).Msg("finalize: InfiniBand/IPoIB configuration written")
	}

	return nil
}

// applyBMCConfig configures the local BMC via ipmitool.
// This targets the physical BMC of the node being finalized, not the chroot.
func applyBMCConfig(ctx context.Context, bmc *api.BMCNodeConfig) error {
	c := &ipmi.Client{} // local BMC — no host flags

	bmcCfg := ipmi.BMCConfig{
		Channel:   1,
		IPAddress: bmc.IPAddress,
		Netmask:   bmc.Netmask,
		Gateway:   bmc.Gateway,
		IPSource:  "static",
	}
	if err := c.SetBMCNetwork(ctx, bmcCfg); err != nil {
		return fmt.Errorf("set bmc network: %w", err)
	}

	if bmc.Username != "" && bmc.Password != "" {
		// Use user slot 2 — slot 1 is typically the reserved anonymous user.
		if err := c.SetBMCUser(ctx, 2, bmc.Username, bmc.Password); err != nil {
			return fmt.Errorf("set bmc user: %w", err)
		}
	}
	return nil
}

// writeIBConfig writes IPoIB NetworkManager connection profiles and udev rules
// for each InfiniBand device into the deployed filesystem at mountRoot.
func writeIBConfig(mountRoot string, ibCfgs []api.IBInterfaceConfig) error {
	nmDir := filepath.Join(mountRoot, "etc", "NetworkManager", "system-connections")
	if err := os.MkdirAll(nmDir, 0o700); err != nil {
		return fmt.Errorf("mkdir NM connections: %w", err)
	}

	for _, ib := range ibCfgs {
		if err := writeIPoIBProfile(nmDir, ib); err != nil {
			return fmt.Errorf("ib device %s: %w", ib.DeviceName, err)
		}
	}
	return nil
}

// writeIPoIBProfile writes a NetworkManager keyfile for an IPoIB interface.
// The interface name is derived from the IB device name (e.g. mlx5_0 → ib0).
func writeIPoIBProfile(nmDir string, ib api.IBInterfaceConfig) error {
	// IPoIB interface naming: mlx5_0→ib0, mlx5_1→ib1, hfi1_0→ib0, etc.
	// We use the device name directly as the NM connection id and interface-name.
	ifaceName := ibDeviceToIPoIBName(ib.DeviceName)

	// Validate the derived interface name before using it as a filename component.
	if !ifaceNameRe.MatchString(ifaceName) {
		return fmt.Errorf("derived IB interface name %q contains invalid characters", ifaceName)
	}

	mtu := ib.MTU
	if mtu == 0 {
		if strings.EqualFold(ib.IPoIBMode, "connected") {
			mtu = 65520
		} else {
			mtu = 2044 // datagram mode default
		}
	}

	mode := strings.ToLower(ib.IPoIBMode)
	if mode == "" {
		mode = "datagram"
	}

	var sb strings.Builder
	sb.WriteString("[connection]\n")
	fmt.Fprintf(&sb, "id=%s\n", ifaceName)
	sb.WriteString("type=infiniband\n")
	fmt.Fprintf(&sb, "interface-name=%s\n", ifaceName)
	sb.WriteString("\n")

	sb.WriteString("[infiniband]\n")
	fmt.Fprintf(&sb, "transport-mode=%s\n", mode)
	fmt.Fprintf(&sb, "mtu=%d\n", mtu)
	if len(ib.PKeys) > 0 {
		// Write the first partition key; additional pkeys require separate profiles.
		fmt.Fprintf(&sb, "p-key=%s\n", ib.PKeys[0])
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv4]\n")
	if ib.IPAddress != "" {
		ip, prefix := parseIPCIDR(ib.IPAddress)
		sb.WriteString("method=manual\n")
		fmt.Fprintf(&sb, "address1=%s/%s\n", ip, prefix)
	} else {
		sb.WriteString("method=disabled\n")
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv6]\n")
	sb.WriteString("method=ignore\n")

	filename := filepath.Join(nmDir, ifaceName+".nmconnection")
	return os.WriteFile(filename, []byte(sb.String()), 0o600)
}

// ibDeviceToIPoIBName maps an IB device name to its IPoIB interface name.
// e.g. "mlx5_0" → "ib0", "mlx5_1" → "ib1", "hfi1_0" → "ib0"
func ibDeviceToIPoIBName(devName string) string {
	// Extract trailing digit after the last underscore for the IB port index.
	idx := strings.LastIndex(devName, "_")
	if idx >= 0 && idx < len(devName)-1 {
		suffix := devName[idx+1:]
		// Only use the numeric suffix as the ib interface index.
		allDigits := true
		for _, c := range suffix {
			if c < '0' || c > '9' {
				allDigits = false
				break
			}
		}
		if allDigits {
			return "ib" + suffix
		}
	}
	return "ib0"
}

// writeHostname writes /etc/hostname and updates /etc/hosts.
func writeHostname(mountRoot, hostname, fqdn string) error {
	if hostname == "" {
		return nil
	}

	hostnameFile := filepath.Join(mountRoot, "etc", "hostname")
	if err := os.MkdirAll(filepath.Dir(hostnameFile), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(hostnameFile, []byte(hostname+"\n"), 0o644); err != nil {
		return fmt.Errorf("write /etc/hostname: %w", err)
	}

	// Update /etc/hosts: add or replace the 127.0.1.1 line.
	hostsFile := filepath.Join(mountRoot, "etc", "hosts")
	existing, err := os.ReadFile(hostsFile)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read /etc/hosts: %w", err)
	}

	// Build the new hosts content.
	var lines []string
	for _, line := range strings.Split(string(existing), "\n") {
		// Remove any existing 127.0.1.1 lines.
		if strings.HasPrefix(strings.TrimSpace(line), "127.0.1.1") {
			continue
		}
		lines = append(lines, line)
	}

	entry := "127.0.1.1\t" + hostname
	if fqdn != "" && fqdn != hostname {
		entry = "127.0.1.1\t" + fqdn + "\t" + hostname
	}
	lines = append(lines, entry)

	content := strings.Join(lines, "\n")
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return os.WriteFile(hostsFile, []byte(content), 0o644)
}

// writeNetworkConfig writes NetworkManager keyfile connections for each interface.
// This is the standard config format on Rocky Linux 8/9/10, RHEL 8/9/10, and derivatives.
//
// When interfaces is empty a single fallback "wired-dhcp" connection is written
// that matches any wired interface (no interface-name restriction) and requests a
// DHCP lease. This ensures the node is reachable after first boot even when the
// caller does not specify explicit interface config. Without this, Rocky Linux 10
// will not configure any NIC by default because NM's no-auto-default behavior
// is distribution-controlled and may not activate wired devices automatically.
func writeNetworkConfig(mountRoot string, interfaces []api.InterfaceConfig) error {
	nmDir := filepath.Join(mountRoot, "etc", "NetworkManager", "system-connections")
	if err := os.MkdirAll(nmDir, 0o700); err != nil {
		return fmt.Errorf("mkdir NM connections: %w", err)
	}

	if len(interfaces) == 0 {
		// Write a wildcard DHCP profile so the first wired interface comes up.
		fallback := `[connection]
id=wired-dhcp
type=ethernet
autoconnect=true
autoconnect-priority=-100

[ethernet]

[ipv4]
method=auto

[ipv6]
method=ignore
`
		path := filepath.Join(nmDir, "wired-dhcp.nmconnection")
		return os.WriteFile(path, []byte(fallback), 0o600)
	}

	for _, iface := range interfaces {
		if err := writeNMKeyfile(nmDir, iface); err != nil {
			return fmt.Errorf("interface %s: %w", iface.Name, err)
		}
	}
	return nil
}

// writeNMKeyfile writes a single NetworkManager keyfile for an interface.
func writeNMKeyfile(nmDir string, iface api.InterfaceConfig) error {
	name := iface.Name
	if name == "" {
		name = iface.MACAddress
	}

	// Validate the interface name before using it as a filename component.
	if !ifaceNameRe.MatchString(name) {
		return fmt.Errorf("interface name %q contains invalid characters (must match ^[a-zA-Z0-9._:-]+$)", name)
	}

	// Parse IP and prefix from CIDR.
	ip, prefix := parseIPCIDR(iface.IPAddress)

	var sb strings.Builder
	sb.WriteString("[connection]\n")
	fmt.Fprintf(&sb, "id=%s\n", name)
	fmt.Fprintf(&sb, "type=ethernet\n")
	fmt.Fprintf(&sb, "interface-name=%s\n", name)
	sb.WriteString("\n")

	sb.WriteString("[ethernet]\n")
	if iface.MACAddress != "" {
		fmt.Fprintf(&sb, "mac-address=%s\n", iface.MACAddress)
	}
	if iface.MTU > 0 {
		fmt.Fprintf(&sb, "mtu=%d\n", iface.MTU)
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv4]\n")
	if ip != "" {
		sb.WriteString("method=manual\n")
		fmt.Fprintf(&sb, "address1=%s/%s", ip, prefix)
		if iface.Gateway != "" {
			fmt.Fprintf(&sb, ",%s", iface.Gateway)
		}
		sb.WriteString("\n")
		if len(iface.DNS) > 0 {
			fmt.Fprintf(&sb, "dns=%s;\n", strings.Join(iface.DNS, ";"))
		}
	} else {
		sb.WriteString("method=auto\n")
	}
	sb.WriteString("\n")

	sb.WriteString("[ipv6]\n")
	sb.WriteString("method=ignore\n")

	filename := filepath.Join(nmDir, name+".nmconnection")
	// Mode 0600 is required by NM — it refuses to load world-readable keyfiles.
	return os.WriteFile(filename, []byte(sb.String()), 0o600)
}

// parseIPCIDR splits "192.168.1.10/24" into ("192.168.1.10", "24").
// Returns ("", "") if the input is empty or malformed.
func parseIPCIDR(cidr string) (ip, prefix string) {
	parts := strings.SplitN(cidr, "/", 2)
	if len(parts) == 2 {
		return parts[0], parts[1]
	}
	if len(parts) == 1 && parts[0] != "" {
		return parts[0], "24" // default /24 if no prefix given
	}
	return "", ""
}

// writeSSHKeys writes authorized_keys for root.
func writeSSHKeys(mountRoot string, keys []string) error {
	sshDir := filepath.Join(mountRoot, "root", ".ssh")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		return fmt.Errorf("mkdir .ssh: %w", err)
	}

	authKeysPath := filepath.Join(sshDir, "authorized_keys")
	content := strings.Join(keys, "\n")
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}

	return os.WriteFile(authKeysPath, []byte(content), 0o600)
}

// applyKernelArgs appends extra kernel args to the GRUB default config.
// It looks for GRUB_CMDLINE_LINUX in /etc/default/grub and appends args.
func applyKernelArgs(ctx context.Context, mountRoot, kernelArgs string) error {
	grubDefault := filepath.Join(mountRoot, "etc", "default", "grub")
	raw, err := os.ReadFile(grubDefault)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // no GRUB config — might be a systemd-boot system
		}
		return fmt.Errorf("read grub config: %w", err)
	}

	content := string(raw)
	updated := false
	var newLines []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "GRUB_CMDLINE_LINUX=") {
			// Strip trailing quote, append args, re-add quote.
			trimmed := strings.TrimSuffix(strings.TrimSpace(line), `"`)
			line = trimmed + " " + kernelArgs + `"`
			updated = true
		}
		newLines = append(newLines, line)
	}

	if !updated {
		// Key not present — append it.
		newLines = append(newLines, fmt.Sprintf(`GRUB_CMDLINE_LINUX="%s"`, kernelArgs))
	}

	newContent := strings.Join(newLines, "\n")
	if err := os.WriteFile(grubDefault, []byte(newContent), 0o644); err != nil {
		return fmt.Errorf("write grub config: %w", err)
	}

	// Note: under the content-only model (ADR-0009), applyBootConfig generates
	// the grub.cfg and BLS entries from scratch AFTER applyNodeConfig runs.
	// The /etc/default/grub edit above is the durable per-node override;
	// applyBootConfig will incorporate it when generating BLS entries (S2-04).
	// We do NOT run grub2-mkconfig here — it would be overwritten immediately
	// and may fail on RAID layouts (diskfilter write restriction).
	return nil
}

// findGrubCfg looks for grub.cfg in common locations within the mount root.
func findGrubCfg(mountRoot string) string {
	candidates := []string{
		"/boot/grub2/grub.cfg",
		"/boot/grub/grub.cfg",
		"/boot/efi/EFI/rocky/grub.cfg",
		"/boot/efi/EFI/redhat/grub.cfg",
		"/boot/efi/EFI/centos/grub.cfg",
	}
	for _, c := range candidates {
		if _, err := os.Stat(filepath.Join(mountRoot, c)); err == nil {
			return c // return path relative to chroot root
		}
	}
	return ""
}

// installKernelInChroot installs the kernel and GRUB2 bootloader packages inside
// the deployed chroot using dnf. This is needed when the image was captured
// without /boot contents (e.g. --one-file-system capture with a separate /boot
// partition on the source). After this function returns, /boot/grub2/grub.cfg
// and at least one vmlinuz + initramfs pair will exist in the chroot.
//
// The function mounts /proc, /sys, and /dev into the chroot before running dnf
// because dnf's scriptlets require these virtual filesystems.
func installKernelInChroot(ctx context.Context, mountRoot, targetDisk string) error {
	log := logger()

	// Bind-mount virtual filesystems required by dnf/rpm scriptlets.
	type bindMount struct{ src, dst string }
	binds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	for _, b := range binds {
		if err := os.MkdirAll(b.dst, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", b.dst, err)
		}
		if out, err := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); err != nil {
			return fmt.Errorf("bind-mount %s → %s: %w\n%s", b.src, b.dst, err, string(out))
		}
	}
	defer func() {
		// Unmount in reverse order.
		for i := len(binds) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", binds[i].dst).Run()
		}
	}()

	// Copy the host's /etc/resolv.conf into the chroot so dnf can reach the network.
	resolvSrc := "/etc/resolv.conf"
	resolvDst := filepath.Join(mountRoot, "etc", "resolv.conf")
	if data, err := os.ReadFile(resolvSrc); err == nil {
		_ = os.WriteFile(resolvDst, data, 0o644)
	}

	// Ensure /tmp exists and is writable inside the chroot.
	// dnf requires /tmp for its download cache and RPM scriptlets.
	// Images captured without /tmp (or with sticky-bit /tmp permissions stripped)
	// will cause dnf to fail with "mkstemp: No such file or directory".
	tmpDir := filepath.Join(mountRoot, "tmp")
	if err := os.MkdirAll(tmpDir, 0o1777); err != nil {
		log.Warn().Err(err).Str("path", tmpDir).Msg("finalize/boot: could not create /tmp in chroot (non-fatal)")
	}
	// Ensure /boot/grub2 directory exists so grub2-mkconfig can write grub.cfg.
	grub2Dir := filepath.Join(mountRoot, "boot", "grub2")
	if err := os.MkdirAll(grub2Dir, 0o755); err != nil {
		log.Warn().Err(err).Str("path", grub2Dir).Msg("finalize/boot: could not create /boot/grub2 in chroot (non-fatal)")
	}

	// Install kernel and grub2-pc inside the deployed chroot.
	// We always use "chroot <mountRoot> dnf" because the initramfs (deployment host)
	// does not have dnf — it must be invoked from within the deployed image, which
	// is a full Rocky Linux 9 system with /usr/bin/dnf present.
	//
	// IMPORTANT: disable all third-party repos (epel, epel-next, etc.) during
	// this install. The initramfs environment has no external DNS resolution and
	// any attempt to reach mirrors.fedoraproject.org or similar will time out and
	// cause dnf to fail. Kernel and grub2 are in the base Rocky repos (baseos,
	// appstream, extras) which are served by the local mirrorlist / fastest-mirror
	// cache inside the chroot, but to be safe we explicitly enable only baseos and
	// appstream and disable everything else.
	packages := []string{"kernel", "grub2-pc", "grub2-tools"}
	log.Info().Strs("packages", packages).Msg("finalize/boot: installing kernel + grub2 via chroot dnf (baseos+appstream only)")
	chrootDnfArgs := append([]string{
		mountRoot, "dnf", "-y",
		"--setopt=install_weak_deps=False",
		"--disablerepo=*",
		"--enablerepo=baseos",
		"--enablerepo=appstream",
		"install",
	}, packages...)
	if err := runAndLog(ctx, "chroot-dnf-kernel-install", exec.CommandContext(ctx, "chroot", chrootDnfArgs...)); err != nil {
		return fmt.Errorf("chroot dnf install kernel+grub2: %w", err)
	}

	// Install GRUB to the target disk MBR now that the grub2-pc package is present.
	// grub2-install needs access to /boot (already mounted) and /dev.
	bootDir := filepath.Join(mountRoot, "boot")
	grubInstallArgs := []string{"--target=i386-pc", "--boot-directory=" + bootDir, "--recheck", targetDisk}
	log.Info().Str("disk", targetDisk).Msg("finalize/boot: re-running grub2-install after kernel install")
	if err := runAndLog(ctx, "grub2-install", exec.CommandContext(ctx, "grub2-install", grubInstallArgs...)); err != nil {
		log.Warn().Err(err).Msg("finalize/boot: grub2-install after kernel install failed (non-fatal)")
	}

	// Generate grub.cfg inside the chroot.
	grubCfgInChroot := "/boot/grub2/grub.cfg"
	log.Info().Str("grub_cfg", grubCfgInChroot).Msg("finalize/boot: generating grub.cfg via chroot grub2-mkconfig")
	mkcfgCmd := exec.CommandContext(ctx, "chroot", mountRoot, "grub2-mkconfig", "-o", grubCfgInChroot)
	if err := runAndLog(ctx, "grub2-mkconfig", mkcfgCmd); err != nil {
		return fmt.Errorf("finalize/boot: grub2-mkconfig after kernel install: %w", err)
	}
	log.Info().Msg("finalize/boot: kernel + grub2 installed and configured")
	return nil
}

// installEFIBootloaderInChroot installs grub2-efi-x64 and shim-x64 inside the
// deployed chroot via dnf. This is required for UEFI images built from ISO where
// the tar archive only contains empty /boot/efi/EFI/rocky/ stub directories —
// the actual EFI binaries (grubx64.efi, shimx64.efi) live on the ESP partition
// of the source system and are never included in the rootfs capture.
//
// After this function returns, /boot/efi/EFI/rocky/grubx64.efi will be present
// on the mounted ESP so that FixEFIBoot's NVRAM entry can point to a real binary.
func installEFIBootloaderInChroot(ctx context.Context, mountRoot string) error {
	log := logger()

	// Bind-mount virtual filesystems required by dnf/rpm scriptlets.
	type bindMount struct{ src, dst string }
	binds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	for _, b := range binds {
		if err := os.MkdirAll(b.dst, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", b.dst, err)
		}
		if out, err := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); err != nil {
			return fmt.Errorf("bind-mount %s → %s: %w\n%s", b.src, b.dst, err, string(out))
		}
	}
	defer func() {
		for i := len(binds) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", binds[i].dst).Run()
		}
	}()

	// Copy /etc/resolv.conf so dnf can reach package mirrors.
	resolvDst := filepath.Join(mountRoot, "etc", "resolv.conf")
	if data, err := os.ReadFile("/etc/resolv.conf"); err == nil {
		_ = os.WriteFile(resolvDst, data, 0o644)
	}

	// Ensure /tmp is writable — required by dnf for its download cache.
	if err := os.MkdirAll(filepath.Join(mountRoot, "tmp"), 0o1777); err != nil {
		log.Warn().Err(err).Msg("finalize/boot: could not create /tmp in chroot (non-fatal)")
	}

	// Ensure the ESP mount point directory exists.
	espDir := filepath.Join(mountRoot, "boot", "efi")
	if err := os.MkdirAll(espDir, 0o700); err != nil {
		log.Warn().Err(err).Str("path", espDir).Msg("finalize/boot: could not create /boot/efi in chroot (non-fatal)")
	}

	// Install grub2-efi-x64 and shim-x64. Their %post scriptlets run grub2-install
	// or copy the EFI binary to /boot/efi/EFI/rocky/grubx64.efi. We also install
	// grub2-efi-x64-modules so grub2-mkconfig can reference them.
	// Only baseos and appstream are enabled — no external mirrors needed.
	packages := []string{"grub2-efi-x64", "shim-x64", "grub2-efi-x64-modules"}
	log.Info().Strs("packages", packages).Msg("finalize/boot: installing EFI bootloader packages via chroot dnf")
	chrootDnfArgs := append([]string{
		mountRoot, "dnf", "-y",
		"--setopt=install_weak_deps=False",
		"--disablerepo=*",
		"--enablerepo=baseos",
		"--enablerepo=appstream",
		"install",
	}, packages...)
	if err := runAndLog(ctx, "chroot-dnf-efi-install", exec.CommandContext(ctx, "chroot", chrootDnfArgs...)); err != nil {
		return fmt.Errorf("chroot dnf install grub2-efi-x64 shim-x64: %w", err)
	}
	log.Info().Msg("finalize/boot: EFI bootloader packages installed")
	return nil
}

// applyBootConfig generates all topology-specific boot state from scratch
// (ADR-0009 content-only model). It must be called after the rootfs tarball has
// been extracted and after grub2-install has written the bootloader MBR/bios-boot.
//
// New flow (generate, do not patch):
//
//  1. Generate a fresh machine-id and write to /etc/machine-id +
//     /var/lib/dbus/machine-id.
//  2. Write /etc/fstab.d/00-clonr-os.fstab with OS-disk mounts, assemble
//     /etc/fstab from all fstab.d files in lexicographic order (§5A split).
//  3. Generate BLS entries from scratch under /boot/loader/entries/ using the
//     new machine-id and target root UUID.
//  4. Prepare the RAID dracut config (if RAID layout).
//  5. Run dracut --regenerate-all --no-hostonly --force inside a chroot to
//     rebuild initramfs with the correct modules for the target hardware.
//  6. Write a minimal hand-crafted grub.cfg (no grub2-mkconfig, no save_env,
//     no submenus — clean bootable config for provisioned compute nodes).
//  7. Scrub SSH host keys so sshd regenerates unique keys on first boot.
//
// All UUID-patch and sed-based code has been deleted. Nothing is patched;
// everything topology-specific is generated fresh from the target partition UUIDs.
//
// partDevs must be in the same order as layout.Partitions (index i → device i+1).
func applyBootConfig(ctx context.Context, mountRoot, targetDisk string, layout api.DiskLayout, partDevs []string) error {
	log := logger()

	// ── 1. Generate fresh machine-id ────────────────────────────────────────
	// Content-only images carry an empty /etc/machine-id placeholder.
	// Generate a 128-bit random hex string and write it now so that BLS entry
	// filenames (which embed the machine-id) are deterministic within this deploy.
	machineID, err := generateMachineID()
	if err != nil {
		return fmt.Errorf("finalize/boot: generate machine-id: %w", err)
	}
	machineIDPath := filepath.Join(mountRoot, "etc", "machine-id")
	if err := os.WriteFile(machineIDPath, []byte(machineID+"\n"), 0o644); err != nil {
		return fmt.Errorf("finalize/boot: write machine-id: %w", err)
	}
	dbusMachineIDPath := filepath.Join(mountRoot, "var", "lib", "dbus", "machine-id")
	if err := os.MkdirAll(filepath.Dir(dbusMachineIDPath), 0o755); err == nil {
		_ = os.WriteFile(dbusMachineIDPath, []byte(machineID+"\n"), 0o444)
	}
	log.Info().Str("machine_id", machineID).Msg("finalize/boot: fresh machine-id generated and written")

	// ── 2. Generate fstab (§5A ownership split) ──────────────────────────────
	// Write OS-disk mounts to /etc/fstab.d/00-clonr-os.fstab, then assemble
	// /etc/fstab from all fstab.d files in lexicographic order.
	// Paths matching /etc/fstab.d/9*-*.fstab are owned by the image overlay and
	// are never overwritten here.
	log.Info().Msg("finalize/boot: generating /etc/fstab.d/00-clonr-os.fstab")
	if err := writeFstabD(ctx, mountRoot, layout, partDevs); err != nil {
		return fmt.Errorf("finalize/boot: fstab generation: %w", err)
	}
	log.Info().Msg("finalize/boot: /etc/fstab assembled from fstab.d")

	// Get the root UUID now — needed for BLS entries and grub.cfg.
	var rootUUID, bootUUID string
	for i, p := range layout.Partitions {
		if i >= len(partDevs) {
			break
		}
		u, uErr := getUUID(ctx, partDevs[i])
		if uErr != nil {
			log.Warn().Err(uErr).Str("device", partDevs[i]).Str("mp", p.MountPoint).
				Msg("finalize/boot: could not get UUID for partition")
			continue
		}
		switch p.MountPoint {
		case "/":
			rootUUID = u
		case "/boot":
			bootUUID = u
		}
	}
	if rootUUID == "" {
		return fmt.Errorf("finalize/boot: could not determine root partition UUID — deploy cannot continue")
	}
	// When /boot is not a separate partition, grub reads from root.
	if bootUUID == "" {
		bootUUID = rootUUID
	}
	log.Info().Str("root_uuid", rootUUID).Str("boot_uuid", bootUUID).
		Msg("finalize/boot: partition UUIDs resolved")

	// ── 3. Discover kernels and generate BLS entries ─────────────────────────
	// List all vmlinuz-* files under /boot to enumerate installed kernels.
	// One BLS entry is generated per kernel with the fresh machine-id.
	log.Info().Msg("finalize/boot: generating BLS boot entries")
	if err := generateBLSEntries(mountRoot, machineID, rootUUID, layout); err != nil {
		// Non-fatal: if BLS fails the hand-crafted grub.cfg below still boots
		// the first kernel it finds directly. Log loudly so the operator knows.
		log.Warn().Err(err).Msg("WARNING finalize/boot: BLS entry generation failed — node will boot via direct grub.cfg menuentry")
	}

	// ── 4. RAID dracut prep (if RAID layout) ────────────────────────────────
	// Inject mdraid dracut module config, mdadm binary, and udev rules into the
	// chroot so dracut builds an initramfs that can assemble md arrays on first boot.
	if len(layout.RAIDArrays) > 0 {
		if err := prepareDracutForRAID(mountRoot, layout); err != nil {
			log.Warn().Err(err).Msg("finalize/boot: RAID dracut prep failed (non-fatal)")
		}
	}

	// Ensure the standard virtual filesystem mount points exist in the deployed
	// root before calling dracut. These directories are NOT present in tar
	// archives captured via rsync (rsync skips empty stub directories for virtual
	// mounts like /proc, /sys, /dev). Without them, bind-mounts fail with ENOENT.
	for _, dir := range []string{"proc", "sys", "dev", "dev/pts", "run", "var/tmp"} {
		target := filepath.Join(mountRoot, dir)
		if err := os.MkdirAll(target, 0o755); err != nil {
			log.Warn().Err(err).Str("dir", target).Msg("finalize/boot: could not create chroot mount dir (non-fatal)")
		}
	}

	// ── 5. Bind-mount virtual filesystems and rebuild initramfs via dracut ───
	// dracut's module-setup.sh scripts inspect /proc/cpuinfo, /sys/module/*,
	// and /dev/fd to detect hardware and build the correct initramfs.
	// Without these bind-mounts, dracut warns "/proc/ is not mounted" and may
	// omit critical modules (XFS, virtio_scsi, etc.) from the initramfs.
	type bindMount struct{ src, dst string }
	dracutBinds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	var mountedPaths []string
	for _, b := range dracutBinds {
		if out, mountErr := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); mountErr != nil {
			log.Warn().Err(mountErr).Str("src", b.src).Str("dst", b.dst).
				Str("output", string(out)).Msg("finalize/boot: bind-mount failed — dracut may omit hardware modules (non-fatal)")
		} else {
			mountedPaths = append(mountedPaths, b.dst)
		}
	}
	defer func() {
		for i := len(mountedPaths) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", mountedPaths[i]).Run()
		}
	}()

	// --no-hostonly: build a generic initramfs (hardware-agnostic, not tailored
	// to the deploy host's physical devices). Required because we are running in
	// a PXE initramfs environment with different hardware than the target node.
	// --force: overwrite any existing initramfs images without prompting.
	// --regenerate-all: rebuild for every installed kernel version.
	log.Info().Msg("finalize/boot: rebuilding initramfs via dracut --no-hostonly --regenerate-all")
	dracutCmd := exec.CommandContext(ctx, "chroot", mountRoot,
		"dracut", "--force", "--no-hostonly", "--regenerate-all")
	if err := runAndLog(ctx, "dracut", dracutCmd); err != nil {
		log.Warn().Err(err).
			Msg("WARNING finalize/boot: dracut --regenerate-all failed — initramfs may lack hardware drivers for target; node may not boot on different hardware")
	} else {
		log.Info().Msg("finalize/boot: dracut complete")
	}

	// ── 6. Pin GRUB default to the production kernel ────────────────────────
	// dracut --regenerate-all writes a rescue BLS entry whose filename starts
	// with "0-rescue-", which sorts lexicographically before production kernel
	// entries. On BIOS RAID1 (VM206) Rocky's GRUB2 has BLS support compiled in
	// and auto-loads all entries from /boot/loader/entries/; without explicit
	// pinning it picks entry 0 — the rescue initramfs — which lacks mdraid
	// assembly modules and hangs at "Probing EDD".
	//
	// We write grubenv directly (grub2-editenv is not staged in the deploy
	// initramfs) and update grub.cfg to honour saved_entry via load_env.
	log.Info().Msg("finalize/boot: pinning GRUB saved_entry to production kernel")
	savedEntry, pinErr := pinGrubDefaultBLSEntry(mountRoot)
	if pinErr != nil {
		// Non-fatal: grub.cfg still boots explicitly via menuentry. Log loudly
		// so operators know the RAID1 rescue-hang risk is not mitigated.
		log.Warn().Err(pinErr).Msg("WARNING finalize/boot: could not pin GRUB saved_entry (non-fatal, but RAID1 may boot rescue kernel)")
	} else {
		log.Info().Str("saved_entry", savedEntry).Msg("finalize/boot: GRUB saved_entry pinned to production kernel")
	}

	// ── 7. Write minimal hand-crafted grub.cfg ──────────────────────────────
	// Do NOT run grub2-mkconfig: it produces save_env / saved_entry calls that
	// fail on BIOS RAID (diskfilter writes are not supported) and injects
	// unnecessary multi-boot / rescue complexity. We generate a minimal config
	// directly from the discovered kernels and target UUIDs.
	log.Info().Msg("finalize/boot: writing minimal hand-crafted grub.cfg")
	if err := writeHandcraftedGrubCfg(mountRoot, rootUUID, bootUUID, layout); err != nil {
		// Non-fatal: the node can still attempt to boot via BLS entries.
		log.Warn().Err(err).Msg("WARNING finalize/boot: could not write grub.cfg (non-fatal if BLS is active)")
	} else {
		log.Info().Msg("finalize/boot: grub.cfg written")
	}

	// ── 8. SSH host key scrub ────────────────────────────────────────────────
	// Remove host keys baked into the image so sshd regenerates unique keys
	// on first boot via the ssh-keygen firstboot unit.
	hostKeys, _ := filepath.Glob(filepath.Join(mountRoot, "etc", "ssh", "ssh_host_*"))
	for _, k := range hostKeys {
		if err := os.Remove(k); err != nil {
			log.Warn().Err(err).Str("key", k).
				Msg("finalize/boot: could not remove SSH host key (non-fatal)")
		}
	}
	if len(hostKeys) > 0 {
		log.Info().Int("count", len(hostKeys)).
			Msg("finalize/boot: SSH host keys removed — sshd will regenerate on first boot")
	}

	return nil
}

// generateMachineID returns a fresh 128-bit random hex string suitable for
// /etc/machine-id (32 lowercase hex chars, no hyphens, no newline).
func generateMachineID() (string, error) {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("read random bytes: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// writeFstabD writes /etc/fstab.d/00-clonr-os.fstab with OS-disk mounts only
// (root, /boot, swap, /boot/efi), then assembles /etc/fstab by concatenating
// all fstab.d files in lexicographic order (ADR-0009 §5A ownership split).
//
// Files matching /etc/fstab.d/9*-*.fstab are owned by the image overlay and
// are NEVER touched here. /etc/fstab itself is always regenerated.
func writeFstabD(ctx context.Context, mountRoot string, layout api.DiskLayout, partDevs []string) error {
	log := logger()

	fstabDDir := filepath.Join(mountRoot, "etc", "fstab.d")
	if err := os.MkdirAll(fstabDDir, 0o755); err != nil {
		return fmt.Errorf("mkdir fstab.d: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# /etc/fstab.d/00-clonr-os.fstab — OS-disk mounts generated by clonr\n")
	sb.WriteString("# DO NOT EDIT: regenerated on every reimage\n")
	sb.WriteString("# <device>  <mountpoint>  <fstype>  <options>  <dump>  <pass>\n\n")

	for i, p := range layout.Partitions {
		if p.MountPoint == "" {
			continue
		}
		switch p.Filesystem {
		case "", "biosboot", "bios_grub":
			continue
		}
		if i >= len(partDevs) {
			log.Warn().Int("partition", i+1).Msg("writeFstabD: partDevs slice shorter than layout — skipping")
			continue
		}

		uuid, err := getUUID(ctx, partDevs[i])
		if err != nil {
			return fmt.Errorf("partition %d (%s): %w", i+1, partDevs[i], err)
		}

		opts := fstabMountOpts(p.Filesystem, p.MountPoint)

		dump := 0
		pass := 0
		switch p.MountPoint {
		case "/":
			dump, pass = 1, 1
		case "/boot":
			dump, pass = 1, 2
		}

		if p.Filesystem == "swap" {
			fmt.Fprintf(&sb, "UUID=%-36s  %-12s  %-6s  %-20s  %d  %d\n",
				uuid, "swap", "swap", "defaults", 0, 0)
		} else {
			fmt.Fprintf(&sb, "UUID=%-36s  %-12s  %-6s  %-20s  %d  %d\n",
				uuid, p.MountPoint, p.Filesystem, opts, dump, pass)
		}
		log.Info().Str("uuid", uuid).Str("mountpoint", p.MountPoint).
			Str("device", partDevs[i]).Msg("finalize/boot: fstab.d entry written")
	}

	osFstabPath := filepath.Join(fstabDDir, "00-clonr-os.fstab")
	if err := os.WriteFile(osFstabPath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("write 00-clonr-os.fstab: %w", err)
	}

	// Assemble /etc/fstab from all fstab.d files in lexicographic order.
	// Files matching 9*-*.fstab are image-overlay-owned — include them but NEVER overwrite.
	entries, err := os.ReadDir(fstabDDir)
	if err != nil {
		return fmt.Errorf("read fstab.d: %w", err)
	}

	var assembled strings.Builder
	assembled.WriteString("# /etc/fstab — assembled by clonr from /etc/fstab.d/*.fstab\n\n")
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".fstab") {
			continue
		}
		data, readErr := os.ReadFile(filepath.Join(fstabDDir, e.Name()))
		if readErr != nil {
			log.Warn().Err(readErr).Str("file", e.Name()).Msg("finalize/boot: could not read fstab.d fragment (skipping)")
			continue
		}
		assembled.Write(data)
		assembled.WriteString("\n")
	}

	fstabPath := filepath.Join(mountRoot, "etc", "fstab")
	if err := os.WriteFile(fstabPath, []byte(assembled.String()), 0o644); err != nil {
		return fmt.Errorf("write /etc/fstab: %w", err)
	}
	return nil
}

// generateBLSEntries creates a Boot Loader Specification entry for each kernel
// found under /boot/vmlinuz-* in the deployed rootfs. Each entry is written to
// /boot/loader/entries/<machineID>-<kver>.conf with the target root UUID on the
// options line and no save_env / submenus.
func generateBLSEntries(mountRoot, machineID, rootUUID string, layout api.DiskLayout) error {
	log := logger()

	bootDir := filepath.Join(mountRoot, "boot")
	entries, err := os.ReadDir(bootDir)
	if err != nil {
		return fmt.Errorf("read /boot: %w", err)
	}

	blsDir := filepath.Join(mountRoot, "boot", "loader", "entries")
	if err := os.MkdirAll(blsDir, 0o755); err != nil {
		return fmt.Errorf("mkdir BLS entries dir: %w", err)
	}

	// Build base kernel cmdline: console + RAID UUIDs if applicable.
	baseOpts := []string{"ro", "console=ttyS0,115200"}
	if len(layout.RAIDArrays) > 0 {
		baseOpts = append(baseOpts, "rd.auto")
		for _, spec := range layout.RAIDArrays {
			mdDev := "/dev/" + spec.Name
			ctx := context.Background()
			uuid, uuidErr := getRaidArrayUUID(ctx, mdDev)
			if uuidErr != nil {
				log.Warn().Err(uuidErr).Str("device", mdDev).
					Msg("finalize/boot: could not get RAID array UUID — rd.md.uuid will be missing from BLS entry")
			} else if uuid != "" {
				baseOpts = append(baseOpts, "rd.md.uuid="+uuid)
			}
		}
	}

	written := 0
	for _, e := range entries {
		name := e.Name()
		if !strings.HasPrefix(name, "vmlinuz-") {
			continue
		}
		kver := strings.TrimPrefix(name, "vmlinuz-")
		if kver == "" {
			continue
		}

		// Check for a matching initramfs.
		initramfsName := "initramfs-" + kver + ".img"
		initramfsPath := filepath.Join(bootDir, initramfsName)
		if _, statErr := os.Stat(initramfsPath); statErr != nil {
			// dracut may not have run yet or may have named it differently.
			// Write the BLS entry anyway with the expected initramfs path;
			// dracut will create it when it runs (step 5 in applyBootConfig).
			log.Warn().Str("kver", kver).Str("expected", initramfsName).
				Msg("finalize/boot: initramfs not found — BLS entry will reference it anyway (dracut will create it)")
		}

		opts := append([]string{"root=UUID=" + rootUUID}, baseOpts...)
		optLine := strings.Join(opts, " ")

		blsContent := fmt.Sprintf(`title Rocky Linux (%s)
version %s
linux /vmlinuz-%s
initrd /initramfs-%s.img
options %s
`, kver, kver, kver, kver, optLine)

		blsPath := filepath.Join(blsDir, machineID+"-"+kver+".conf")
		if err := os.WriteFile(blsPath, []byte(blsContent), 0o644); err != nil {
			log.Warn().Err(err).Str("path", blsPath).Msg("finalize/boot: could not write BLS entry")
			continue
		}
		log.Info().Str("kver", kver).Str("root_uuid", rootUUID).
			Msg("finalize/boot: BLS entry generated")
		written++
	}

	if written == 0 {
		return fmt.Errorf("no kernels found under /boot/vmlinuz-* — cannot generate BLS entries")
	}
	log.Info().Int("count", written).Msg("finalize/boot: BLS entries generated")
	return nil
}

// writeHandcraftedGrubCfg writes a minimal grub.cfg that boots the first
// available kernel without save_env, saved_entry, load_env, or submenus.
// This config is safe on BIOS RAID (diskfilter read-only) and UEFI alike.
//
// On UEFI+BLS systems the BLS entries take precedence; this grub.cfg acts as
// a fallback for non-BLS-capable grub builds.
func writeHandcraftedGrubCfg(mountRoot, rootUUID, bootUUID string, layout api.DiskLayout) error {
	log := logger()

	bootDir := filepath.Join(mountRoot, "boot")
	entries, err := os.ReadDir(bootDir)
	if err != nil {
		return fmt.Errorf("read /boot: %w", err)
	}

	// Find the first kernel.
	var kver string
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), "vmlinuz-") {
			kver = strings.TrimPrefix(e.Name(), "vmlinuz-")
			break
		}
	}
	if kver == "" {
		return fmt.Errorf("no kernel found under /boot/vmlinuz-* — cannot write grub.cfg")
	}

	// Build kernel cmdline.
	cmdlineOpts := []string{"root=UUID=" + rootUUID, "ro", "console=ttyS0,115200"}
	if len(layout.RAIDArrays) > 0 {
		cmdlineOpts = append(cmdlineOpts, "rd.auto")
		for _, spec := range layout.RAIDArrays {
			mdDev := "/dev/" + spec.Name
			ctx := context.Background()
			uuid, uuidErr := getRaidArrayUUID(ctx, mdDev)
			if uuidErr != nil {
				log.Warn().Err(uuidErr).Str("device", mdDev).
					Msg("finalize/boot: grub.cfg: could not get RAID array UUID — rd.md.uuid will be missing")
			} else if uuid != "" {
				cmdlineOpts = append(cmdlineOpts, "rd.md.uuid="+uuid)
			}
		}
	}
	cmdline := strings.Join(cmdlineOpts, " ")

	// Determine if the /boot filesystem module is needed.
	// Default to ext2 for grub (covers both xfs and ext4 — grub uses ext2 module for ext4 too).
	grubBootFSMod := "ext2"
	for _, p := range layout.Partitions {
		if p.MountPoint == "/" || p.MountPoint == "/boot" {
			switch p.Filesystem {
			case "xfs":
				grubBootFSMod = "xfs"
			}
		}
	}

	var cfg strings.Builder
	cfg.WriteString("# /boot/grub2/grub.cfg — generated by clonr (content-only deploy)\n")
	cfg.WriteString("# DO NOT EDIT: regenerated on every reimage\n\n")
	// load_env reads saved_entry from grubenv (written by pinGrubDefaultBLSEntry).
	// On BIOS RAID diskfilter allows reads but not writes, so we use load_env
	// (read-only) rather than save_env. This pins GRUB to the production kernel
	// BLS entry even when Rocky's built-in BLS loader auto-adds rescue entries
	// that would otherwise sort to index 0.
	cfg.WriteString("load_env\n")
	cfg.WriteString("set default=\"${saved_entry}\"\n")
	cfg.WriteString("set timeout=5\n")
	cfg.WriteString("insmod gzio\n")
	cfg.WriteString("insmod part_gpt\n")
	fmt.Fprintf(&cfg, "insmod %s\n", grubBootFSMod)
	// RAID layouts need diskfilter module to read /boot from the md array.
	if len(layout.RAIDArrays) > 0 {
		cfg.WriteString("insmod diskfilter\n")
		cfg.WriteString("insmod mdraid1x\n")
	}
	fmt.Fprintf(&cfg, "search --no-floppy --fs-uuid --set=root %s\n\n", bootUUID)

	// Kernel path relative to GRUB root:
	// - When /boot is a separate partition (bootUUID != rootUUID), GRUB's root IS
	//   the /boot partition, so kernel is at /vmlinuz-<kver> (not /boot/vmlinuz-).
	// - When /boot is on the root partition (bootUUID == rootUUID), GRUB's root IS
	//   the root partition, so kernel is at /boot/vmlinuz-<kver>.
	kernelPrefix := "/boot"
	if bootUUID != rootUUID {
		kernelPrefix = ""
	}
	fmt.Fprintf(&cfg, "menuentry \"Rocky Linux (%s)\" {\n", kver)
	fmt.Fprintf(&cfg, "  linux %s/vmlinuz-%s %s\n", kernelPrefix, kver, cmdline)
	fmt.Fprintf(&cfg, "  initrd %s/initramfs-%s.img\n", kernelPrefix, kver)
	cfg.WriteString("}\n")

	grubCfgPath := filepath.Join(mountRoot, "boot", "grub2", "grub.cfg")
	if err := os.MkdirAll(filepath.Dir(grubCfgPath), 0o755); err != nil {
		return fmt.Errorf("mkdir grub2 dir: %w", err)
	}
	if err := os.WriteFile(grubCfgPath, []byte(cfg.String()), 0o644); err != nil {
		return fmt.Errorf("write grub.cfg: %w", err)
	}
	log.Info().Str("kver", kver).Str("root_uuid", rootUUID).
		Msg("finalize/boot: hand-crafted grub.cfg written")
	return nil
}

// prepareDracutForRAID injects the mdraid dracut configuration, mdadm binary,
// and md udev rules into the deployed chroot so dracut can build an initramfs
// that assembles md RAID arrays before mounting root on first boot.
func prepareDracutForRAID(mountRoot string, layout api.DiskLayout) error {
	log := logger()

	dracutConfDir := filepath.Join(mountRoot, "etc", "dracut.conf.d")
	if err := os.MkdirAll(dracutConfDir, 0o755); err != nil {
		return fmt.Errorf("mkdir dracut.conf.d: %w", err)
	}

	dracutRAIDConf := filepath.Join(dracutConfDir, "10-clonr-mdraid.conf")
	confContent := `# Written by clonr during deployment for RAID layouts.
# Forces mdraid dracut module to be included in the initramfs so the OS can
# assemble its md RAID arrays before mounting root on first boot.
add_dracutmodules+=" mdraid "
# mdadmconf=yes tells dracut to copy /etc/mdadm.conf into the initramfs so
# mdadm can assemble arrays by UUID without requiring rd.md.uuid= cmdline args.
mdadmconf=yes
`
	if err := os.WriteFile(dracutRAIDConf, []byte(confContent), 0o644); err != nil {
		return fmt.Errorf("write mdraid dracut config: %w", err)
	}
	log.Info().Str("path", dracutRAIDConf).
		Msg("finalize/boot: wrote mdraid dracut config")

	// Inject mdadm binary if absent.
	chrootMdadm := filepath.Join(mountRoot, "usr", "sbin", "mdadm")
	if _, err := os.Stat(chrootMdadm); os.IsNotExist(err) {
		hostMdadm, lookErr := exec.LookPath("mdadm")
		if lookErr != nil {
			log.Warn().Msg("finalize/boot: mdadm not found on deploy host — dracut mdraid module may fail")
		} else {
			if copyErr := copyFile(hostMdadm, chrootMdadm, 0o755); copyErr != nil {
				log.Warn().Err(copyErr).Msg("finalize/boot: could not inject mdadm into chroot")
			} else {
				log.Info().Str("dst", chrootMdadm).Msg("finalize/boot: injected mdadm into chroot")
			}
		}
	}

	// Inject mdadm udev rules.
	chrootUdevRulesDir := filepath.Join(mountRoot, "usr", "lib", "udev", "rules.d")
	if err := os.MkdirAll(chrootUdevRulesDir, 0o755); err != nil {
		return fmt.Errorf("mkdir udev rules.d: %w", err)
	}
	for _, ruleSpec := range []struct {
		name    string
		content string
	}{
		{"63-md-raid-arrays.rules", mdRaidArraysRules},
		{"64-md-raid-assembly.rules", mdRaidAssemblyRules},
	} {
		chrootRule := filepath.Join(chrootUdevRulesDir, ruleSpec.name)
		if _, statErr := os.Stat(chrootRule); statErr == nil {
			log.Info().Str("file", ruleSpec.name).
				Msg("finalize/boot: mdadm udev rule already present — skipping injection")
			continue
		}
		if err := os.WriteFile(chrootRule, []byte(ruleSpec.content), 0o644); err != nil {
			log.Warn().Err(err).Str("dst", chrootRule).
				Msg("finalize/boot: could not write mdadm udev rule (non-fatal)")
		} else {
			log.Info().Str("file", ruleSpec.name).
				Msg("finalize/boot: wrote mdadm udev rule into chroot")
		}
	}
	return nil
}


// getUUID returns the filesystem UUID of a block device using blkid.
// Returns an error if blkid is unavailable or the device has no UUID (e.g.
// unformatted or a bios_grub partition).
func getUUID(ctx context.Context, device string) (string, error) {
	out, err := exec.CommandContext(ctx, "blkid", "-s", "UUID", "-o", "value", device).Output()
	if err != nil {
		return "", fmt.Errorf("blkid %s: %w", device, err)
	}
	uuid := strings.TrimSpace(string(out))
	if uuid == "" {
		return "", fmt.Errorf("blkid %s: no UUID (partition may be unformatted)", device)
	}
	return uuid, nil
}

// writeFstab is superseded by writeFstabD (ADR-0009 §5A fstab.d ownership split).
// Kept as a shim that delegates to writeFstabD so any call-site not yet updated
// continues to compile. New callers must use writeFstabD directly.
func writeFstab(ctx context.Context, mountRoot string, layout api.DiskLayout, partDevs []string) error {
	return writeFstabD(ctx, mountRoot, layout, partDevs)
}

// fstabMountOpts returns appropriate mount options for a given filesystem type
// and mountpoint. These are conservative production defaults for Rocky Linux 9.
func fstabMountOpts(fstype, mountpoint string) string {
	switch fstype {
	case "xfs":
		if mountpoint == "/" {
			return "defaults,noatime"
		}
		return "defaults"
	case "ext4":
		if mountpoint == "/" {
			return "defaults,noatime"
		}
		return "defaults"
	case "vfat", "fat32":
		return "defaults,uid=0,gid=0,umask=077,shortname=winnt"
	case "swap":
		return "defaults"
	default:
		return "defaults"
	}
}

// applyExtraMounts appends custom fstab entries from NodeConfig.ExtraMounts and
// optionally creates the mount point directories inside the deployed filesystem.
// It must be called after applyBootConfig so the base fstab already exists.
//
// Invalid entries are skipped with a warning rather than aborting the deployment,
// because a bad shared-storage entry should not prevent the node from booting.
func applyExtraMounts(ctx context.Context, mountRoot string, mounts []api.FstabEntry) error {
	if len(mounts) == 0 {
		return nil
	}

	log := logger()

	fstabPath := filepath.Join(mountRoot, "etc", "fstab")
	f, err := os.OpenFile(fstabPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("applyExtraMounts: open fstab: %w", err)
	}
	defer f.Close()

	fmt.Fprintf(f, "\n# Additional mounts from clonr NodeConfig.ExtraMounts\n")

	written := 0
	for _, m := range mounts {
		if err := api.ValidateFstabEntry(m); err != nil {
			log.Warn().Err(err).Str("mount_point", m.MountPoint).
				Msg("finalize: skipping invalid extra fstab entry")
			continue
		}

		// Auto-create the mount point directory inside the deployed filesystem.
		if m.AutoMkdir {
			targetDir := filepath.Join(mountRoot, m.MountPoint)

			// Path traversal guard: the resolved absolute path must remain inside mountRoot.
			absTarget, err := filepath.Abs(targetDir)
			if err != nil || !strings.HasPrefix(absTarget, mountRoot+string(filepath.Separator)) {
				log.Warn().Str("mount_point", m.MountPoint).
					Msg("finalize: mount point escapes deployed filesystem root — skipping mkdir")
			} else if err := os.MkdirAll(absTarget, 0755); err != nil {
				// Non-fatal: the mount will fail at boot, but we still write the entry
				// so the operator can investigate rather than silently losing the config.
				log.Warn().Err(err).Str("path", absTarget).
					Msg("finalize: failed to create extra mount point (non-fatal)")
			} else {
				log.Info().Str("path", m.MountPoint).
					Msg("finalize: created mount point for extra mount")
			}
		}

		// Resolve mount options: default to "defaults" when empty, then auto-inject
		// _netdev for network filesystems that omit it (needed so systemd waits for
		// the network before attempting the mount).
		opts := m.Options
		if opts == "" {
			opts = "defaults"
		}
		if api.IsNetworkFS(m.FSType) && !strings.Contains(opts, "_netdev") {
			opts += ",_netdev"
			log.Info().Str("fs_type", m.FSType).Str("mount_point", m.MountPoint).
				Msg("finalize: auto-added _netdev to extra mount options for network filesystem")
		}

		if m.Comment != "" {
			fmt.Fprintf(f, "# %s\n", m.Comment)
		}
		// fstab format: source  mountpoint  fstype  options  dump  pass
		fmt.Fprintf(f, "%s\t%s\t%s\t%s\t%d\t%d\n",
			m.Source, m.MountPoint, m.FSType, opts, m.Dump, m.Pass)

		log.Info().
			Str("source", m.Source).
			Str("mount_point", m.MountPoint).
			Str("fs_type", m.FSType).
			Msg("finalize: wrote extra fstab entry")
		written++
	}

	log.Info().Int("count", written).Msg("finalize: extra fstab entries written")
	return nil
}

// getRaidArrayUUID returns the UUID of an assembled md RAID array in the
// colon-separated format used by dracut's rd.md.uuid= kernel cmdline parameter
// (e.g. "3c483b47:8a550722:e7c1e792:d426519c").
// It runs "mdadm --detail --export <device>" and extracts the MD_UUID field.
func getRaidArrayUUID(ctx context.Context, mdDev string) (string, error) {
	out, err := exec.CommandContext(ctx, "mdadm", "--detail", "--export", mdDev).Output()
	if err != nil {
		return "", fmt.Errorf("mdadm --detail --export %s: %w", mdDev, err)
	}
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "MD_UUID=") {
			return strings.TrimPrefix(line, "MD_UUID="), nil
		}
	}
	return "", fmt.Errorf("MD_UUID not found in mdadm --detail --export output for %s", mdDev)
}

// copyFile copies src to dst with the given permission bits.
// If dst's parent directory does not exist it is created.
func copyFile(src, dst string, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("copyFile: mkdir: %w", err)
	}
	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("copyFile: open src: %w", err)
	}
	defer in.Close()

	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		return fmt.Errorf("copyFile: open dst: %w", err)
	}
	defer out.Close()

	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("copyFile: copy: %w", err)
	}
	return nil
}
