//go:build deploy_integration

package testutil

import (
	"archive/tar"
	"bytes"
	"io"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// minimalRootfsDirs lists the directory skeleton that every Linux rootfs needs.
var minimalRootfsDirs = []string{
	"etc",
	"boot",
	"proc",
	"sys",
	"dev",
	"run",
	"tmp",
	"var/log",
	"var/run",
	"usr/bin",
	"usr/sbin",
	"sbin",
	"bin",
}

// minimalRootfsFiles maps relative paths to file contents for the fake rootfs.
var minimalRootfsFiles = map[string]string{
	"etc/hostname": "clustr-test-node\n",
	"etc/fstab": "# /etc/fstab — generated by clustr test harness\n" +
		"UUID=00000000-0000-0000-0000-000000000001 /     ext4 defaults 0 1\n",
	"etc/os-release": "NAME=\"Rocky Linux\"\nVERSION_ID=\"9.3\"\nID=rocky\n",
	"boot/grub2/grub.cfg": "# placeholder grub config\n",
	"sbin/init":           "#!/bin/sh\nexec /usr/lib/systemd/systemd\n",
}

// FakeRootfs creates a minimal Linux rootfs directory layout inside a temp
// directory and returns its path. The directory is owned by the test and will
// be removed by the testing package at the end of the test.
//
// sizeMB is accepted for API symmetry with callers that may want to pre-allocate
// a tmpfs; it is not used for the directory-based implementation.
func FakeRootfs(t *testing.T, _ int) string {
	t.Helper()
	root := t.TempDir()

	for _, d := range minimalRootfsDirs {
		if err := os.MkdirAll(filepath.Join(root, d), 0o755); err != nil {
			t.Fatalf("FakeRootfs: mkdir %s: %v", d, err)
		}
	}
	for rel, content := range minimalRootfsFiles {
		full := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("FakeRootfs: mkdir parent of %s: %v", rel, err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatalf("FakeRootfs: write %s: %v", rel, err)
		}
	}
	// Make sbin/init executable so verifyRootfs can check +x.
	_ = os.Chmod(filepath.Join(root, "sbin/init"), 0o755)

	return root
}

// FakeRootfsTar streams a POSIX tar archive of rootfsPath into an io.Reader.
// The tar is buffered in memory — it is sized for small test rootfs trees only.
func FakeRootfsTar(t *testing.T, rootfsPath string) io.Reader {
	t.Helper()
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)

	// Walk the directory tree and emit tar entries.
	err := filepath.Walk(rootfsPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(rootfsPath, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}

		hdr := &tar.Header{
			Name:    rel,
			ModTime: time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC),
		}

		if info.IsDir() {
			hdr.Typeflag = tar.TypeDir
			hdr.Mode = int64(info.Mode())
			return tw.WriteHeader(hdr)
		}

		hdr.Typeflag = tar.TypeReg
		hdr.Mode = int64(info.Mode())
		hdr.Size = info.Size()
		if err := tw.WriteHeader(hdr); err != nil {
			return err
		}

		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer f.Close()
		_, err = io.Copy(tw, f)
		return err
	})
	if err != nil {
		t.Fatalf("FakeRootfsTar: walk %s: %v", rootfsPath, err)
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("FakeRootfsTar: close tar writer: %v", err)
	}
	return &buf
}

// VerifyRootfs asserts that the expected files from the minimal rootfs layout
// exist under path. It calls t.Errorf (not t.Fatalf) for each missing file so
// the caller sees all failures at once.
func VerifyRootfs(t *testing.T, path string) {
	t.Helper()
	required := []string{
		"etc/hostname",
		"etc/fstab",
		"etc/os-release",
		"boot/grub2/grub.cfg",
		"sbin/init",
	}
	for _, rel := range required {
		full := filepath.Join(path, rel)
		if _, err := os.Stat(full); err != nil {
			t.Errorf("VerifyRootfs: expected file %s is missing under %s: %v", rel, path, err)
		}
	}
	// Verify hostname content matches what FakeRootfs wrote.
	hostnameBytes, err := os.ReadFile(filepath.Join(path, "etc/hostname"))
	if err != nil {
		t.Errorf("VerifyRootfs: cannot read etc/hostname: %v", err)
	} else if string(hostnameBytes) != "clustr-test-node\n" {
		t.Errorf("VerifyRootfs: etc/hostname = %q, want %q", hostnameBytes, "clustr-test-node\n")
	}
}
