package handlers

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"github.com/sqoia-dev/clustr/internal/db"
	"github.com/sqoia-dev/clustr/internal/metrics"
	"github.com/sqoia-dev/clustr/internal/webhook"
	"github.com/sqoia-dev/clustr/pkg/api"
)

// sortNodeConfigs sorts a slice of NodeConfigs by the given column name.
// Valid columns: hostname, status, last_deploy, group. Unrecognised columns are no-ops.
func sortNodeConfigs(nodes []api.NodeConfig, col string, desc bool) {
	less := func(i, j int) bool {
		a, b := nodes[i], nodes[j]
		var cmp int
		switch col {
		case "hostname":
			cmp = strings.Compare(strings.ToLower(a.Hostname), strings.ToLower(b.Hostname))
		case "status":
			cmp = strings.Compare(string(a.State()), string(b.State()))
		case "last_deploy":
			// S6-8: sort by deploy_completed_preboot_at (canonical ADR-0008 field).
			ta := a.DeployCompletedPrebootAt
			tb := b.DeployCompletedPrebootAt
			if ta == nil && tb == nil {
				cmp = 0
			} else if ta == nil {
				cmp = -1
			} else if tb == nil {
				cmp = 1
			} else if ta.Before(*tb) {
				cmp = -1
			} else if ta.After(*tb) {
				cmp = 1
			} else {
				cmp = 0
			}
		case "group":
			cmp = strings.Compare(strings.ToLower(a.GroupID), strings.ToLower(b.GroupID))
		default:
			cmp = 0
		}
		if desc {
			return cmp > 0
		}
		return cmp < 0
	}
	sort.SliceStable(nodes, less)
}

// extractIP returns just the IP from a CIDR string like "10.0.1.50/24".
// Returns the input unchanged if no slash is present.
func extractIP(cidr string) string {
	if idx := strings.Index(cidr, "/"); idx >= 0 {
		return cidr[:idx]
	}
	return cidr
}

// autoHostnameRe matches hostnames that were auto-generated by clustr.
// Pattern: clustr-<6 hex digits>, e.g. "clustr-36e92f".
var autoHostnameRe = regexp.MustCompile(`^clustr-[0-9a-f]{6}$`)

// defaultDomain returns the domain to use when building auto-generated FQDNs.
// Override by setting the CLUSTR_DEFAULT_DOMAIN environment variable.
func defaultDomain() string {
	if d := os.Getenv("CLUSTR_DEFAULT_DOMAIN"); d != "" {
		return d
	}
	return "clustr.local"
}

// autoHostname generates a deterministic hostname from the last 6 hex chars of
// the MAC address (last 3 octets, colons stripped).
// E.g. "bc:24:11:36:e9:2f" → "clustr-36e92f".
// Using 6 chars gives 16.7M unique values vs 65,536 with 4 chars.
func autoHostname(mac string) string {
	stripped := strings.ReplaceAll(mac, ":", "")
	if len(stripped) >= 6 {
		return "clustr-" + stripped[len(stripped)-6:]
	}
	return "clustr-" + stripped
}

// NodesHandler handles all /api/v1/nodes routes.
type NodesHandler struct {
	DB    *db.DB
	Audit *db.AuditService
	// GetActorInfo returns (actorID, actorLabel) for the current request.
	GetActorInfo func(r *http.Request) (id, label string)
	// FlipToDiskFirst, when non-nil, is called by VerifyBoot after recording the
	// deployed_verified state transition. It should call
	// SetPersistentBootOrder([BootDisk, BootPXE]) on the node's power provider.
	// This flips the Proxmox VM boot order back to disk-first after a successful
	// deploy (the reimage path set it to PXE-first via SetNextBoot). On IPMI
	// providers this is a harmless no-op. Best-effort: errors are logged but do
	// not fail the verify-boot response — the node is already deployed.
	// See docs/boot-architecture.md §10.
	FlipToDiskFirst func(ctx context.Context, nodeID string) error
	// LDAPNodeConfig, when non-nil, is called during RegisterNode to inject the
	// current LDAP client config into the NodeConfig returned to the deploy agent.
	// Returns nil if the LDAP module is disabled or not ready.
	LDAPNodeConfig func(ctx context.Context) (*api.LDAPNodeConfig, error)
	// RecordNodeLDAPConfigured, when non-nil, is called from DeployComplete to record
	// that a node's LDAP client config was applied and to lock the base DN on first use.
	RecordNodeLDAPConfigured func(ctx context.Context, nodeID, configHash string) error
	// SystemAccountsConfig returns the current set of system accounts/groups for
	// embed in the NodeConfig returned to the deploy agent. Returns nil if none defined.
	SystemAccountsConfig func(ctx context.Context) (*api.SystemAccountsNodeConfig, error)
	// NetworkConfig, when non-nil, is called during RegisterNode to resolve the
	// network profile for the node's group. Returns nil if no profile is assigned.
	NetworkConfig func(ctx context.Context, groupID string) (*api.NetworkNodeConfig, error)
	// SlurmNodeConfig, when non-nil, is called during RegisterNode to inject the
	// rendered Slurm config for the specific node into the NodeConfig returned to
	// the deploy agent. Returns nil if the Slurm module is disabled or not ready.
	SlurmNodeConfig func(ctx context.Context, nodeID string) (*api.SlurmNodeConfig, error)
	// SudoersNodeConfig, when non-nil, is called during RegisterNode to inject the
	// sudoers drop-in config into the NodeConfig returned to the deploy agent.
	// Returns nil if the sudoers feature is disabled or LDAP is not ready.
	SudoersNodeConfig func(ctx context.Context) (*api.SudoersNodeConfig, error)
	// LookupDHCPLease returns the DHCP-assigned IP for a MAC, or nil if no active lease.
	// Used during RegisterNode to auto-populate InterfaceConfig from hardware discovery.
	// May be nil — if so, DHCP lookup is skipped and interfaces are not auto-populated.
	LookupDHCPLease func(mac string) net.IP
	// DHCPSubnetCIDR is the prefix length of the PXE provisioning subnet (e.g. 24).
	// Used when constructing CIDR strings for auto-populated InterfaceConfigs.
	// Defaults to 24 when zero.
	DHCPSubnetCIDR int
	// ServerIP is the clustr server's own IP address (from CLUSTR_PXE_SERVER_IP).
	// When non-empty, it is included in ClusterHosts injected during RegisterNode so
	// deployed nodes can resolve "clustr" in /etc/hosts without depending on DNS.
	ServerIP string
	// WebhookDispatcher, when non-nil, is called to fan out webhook events on
	// deploy-complete, deploy-failed, and verify-boot callbacks (S4-2).
	WebhookDispatcher *webhook.Dispatcher
}

// sanitizeNodeConfig returns cfg with sensitive fields in PowerProvider and BMC
// redacted. Call this on every outbound NodeConfig so credentials never leak in responses.
func sanitizeNodeConfig(cfg api.NodeConfig) api.NodeConfig {
	cfg.PowerProvider = cfg.PowerProvider.Sanitize()
	if cfg.BMC != nil {
		bmc := *cfg.BMC
		bmc.Password = ""
		cfg.BMC = &bmc
	}
	return cfg
}

// sanitizeNodeConfigs applies sanitizeNodeConfig to a slice in place.
func sanitizeNodeConfigs(cfgs []api.NodeConfig) []api.NodeConfig {
	for i := range cfgs {
		cfgs[i] = sanitizeNodeConfig(cfgs[i])
	}
	return cfgs
}

// ListNodes handles GET /api/v1/nodes
// Accepts optional ?page= and ?per_page= (default 50) for pagination.
// When pagination params are absent the full list is returned (backward compatible).
// S5-3: accepts ?sort=hostname|status|last_deploy|group and ?dir=asc|desc.
func (h *NodesHandler) ListNodes(w http.ResponseWriter, r *http.Request) {
	baseImageID := r.URL.Query().Get("base_image_id")
	search := strings.TrimSpace(r.URL.Query().Get("search"))
	sortCol := r.URL.Query().Get("sort")
	sortDir := r.URL.Query().Get("dir")
	// TAG-2: collect all ?tag= values (multiple allowed, AND semantics).
	tagFilter := r.URL.Query()["tag"]
	rawPage, rawPerPage, paging := parsePaginationQuery(r)

	nodes, err := h.DB.SearchNodeConfigs(r.Context(), baseImageID, search, tagFilter)
	if err != nil {
		log.Error().Err(err).Msg("list nodes")
		writeError(w, err)
		return
	}
	if nodes == nil {
		nodes = []api.NodeConfig{}
	}
	nodes = sanitizeNodeConfigs(nodes)

	// S5-3: server-side sort by requested column.
	if sortCol != "" {
		desc := strings.ToLower(sortDir) == "desc"
		sortNodeConfigs(nodes, sortCol, desc)
	}

	total := len(nodes)
	resp := api.ListNodesResponse{Total: total}
	if paging {
		start, end, p := paginate(total, rawPage, rawPerPage)
		resp.Nodes = nodes[start:end]
		resp.Page = p.page
		resp.PerPage = p.perPage
		// NextCursor is the next page number, 0 means no more pages.
		if end < total {
			resp.NextCursor = p.page + 1
		}
	} else {
		resp.Nodes = nodes
	}
	// S6-7: signal that the "groups" field in NodeConfig is deprecated and will
	// be removed in v1.1.
	setNodeConfigSunsetHeader(w)
	writeJSON(w, http.StatusOK, resp)
}

// CreateNode handles POST /api/v1/nodes
func (h *NodesHandler) CreateNode(w http.ResponseWriter, r *http.Request) {
	var req api.CreateNodeConfigRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeValidationError(w, "invalid JSON body")
		return
	}

	if req.Hostname == "" {
		writeValidationError(w, "hostname is required")
		return
	}
	if req.PrimaryMAC == "" {
		writeValidationError(w, "primary_mac is required")
		return
	}
	if req.BaseImageID == "" {
		writeValidationError(w, "base_image_id is required")
		return
	}
	req.PrimaryMAC = strings.ToLower(req.PrimaryMAC)
	if !api.IsValidNodeProvider(req.Provider) {
		writeValidationError(w, "provider must be one of: ipmi, proxmox, or empty string")
		return
	}

	// S2-9: Validate BaseImageID exists before INSERT to surface a clear 400 rather
	// than letting the SQLite FK constraint produce an opaque 500.
	if _, err := h.DB.GetBaseImage(r.Context(), req.BaseImageID); err != nil {
		writeValidationError(w, "image not found: base_image_id does not exist")
		return
	}

	// S2-4: accept both "tags" and deprecated "groups" from the request body.
	reqTags := req.Tags
	if len(reqTags) == 0 && len(req.Groups) > 0 {
		reqTags = req.Groups
	}

	now := time.Now().UTC()
	cfg := api.NodeConfig{
		ID:          uuid.New().String(),
		Hostname:    req.Hostname,
		FQDN:        req.FQDN,
		PrimaryMAC:  req.PrimaryMAC,
		Interfaces:  req.Interfaces,
		SSHKeys:     req.SSHKeys,
		KernelArgs:  req.KernelArgs,
		Tags:        reqTags,
		Groups:      reqTags, // dual-emit: mirror tags into deprecated field
		CustomVars:  req.CustomVars,
		BaseImageID: req.BaseImageID,
		Provider:    req.Provider,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
	if cfg.Interfaces == nil {
		cfg.Interfaces = []api.InterfaceConfig{}
	}
	if cfg.SSHKeys == nil {
		cfg.SSHKeys = []string{}
	}
	if cfg.Tags == nil {
		cfg.Tags = []string{}
		cfg.Groups = []string{}
	}
	if cfg.CustomVars == nil {
		cfg.CustomVars = map[string]string{}
	}

	if err := h.DB.CreateNodeConfig(r.Context(), cfg); err != nil {
		log.Error().Err(err).Msg("create node config")
		writeError(w, err)
		return
	}

	if h.Audit != nil {
		aID, aLabel := "", ""
		if h.GetActorInfo != nil {
			aID, aLabel = h.GetActorInfo(r)
		}
		h.Audit.Record(r.Context(), aID, aLabel, db.AuditActionNodeCreate, "node", cfg.ID,
			r.RemoteAddr, nil, map[string]string{"hostname": cfg.Hostname, "primary_mac": cfg.PrimaryMAC})
	}

	setNodeConfigSunsetHeader(w) // S6-7: "groups" deprecated, removed in v1.1
	writeJSON(w, http.StatusCreated, cfg)
}

// GetNode handles GET /api/v1/nodes/:id
func (h *NodesHandler) GetNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	cfg, err := h.DB.GetNodeConfig(r.Context(), id)
	if err != nil {
		writeError(w, err)
		return
	}
	setNodeConfigSunsetHeader(w) // S6-7: "groups" deprecated, removed in v1.1
	writeJSON(w, http.StatusOK, sanitizeNodeConfig(cfg))
}

// UpdateNode handles PUT /api/v1/nodes/:id
func (h *NodesHandler) UpdateNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	var req api.UpdateNodeConfigRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeValidationError(w, "invalid JSON body")
		return
	}

	if req.Hostname == "" {
		writeValidationError(w, "hostname is required")
		return
	}
	if req.PrimaryMAC == "" {
		writeValidationError(w, "primary_mac is required")
		return
	}
	req.PrimaryMAC = strings.ToLower(req.PrimaryMAC)

	// Fetch to confirm existence.
	existing, err := h.DB.GetNodeConfig(r.Context(), id)
	if err != nil {
		writeError(w, err)
		return
	}

	// Validate extra mount entries before touching the database.
	for i, m := range req.ExtraMounts {
		if err := api.ValidateFstabEntry(m); err != nil {
			writeValidationError(w, fmt.Sprintf("extra_mounts[%d]: %s", i, err.Error()))
			return
		}
	}

	// Resolve the layout override:
	//   - ClearLayoutOverride=true  → explicitly remove override (set nil)
	//   - DiskLayoutOverride present in request → use the new value
	//   - Neither present (omitempty field absent) → preserve existing override
	//     so that a PUT to change hostname/image does not silently wipe a
	//     node-level disk layout that was set via the dedicated override endpoint.
	var layoutOverride *api.DiskLayout
	switch {
	case req.ClearLayoutOverride:
		layoutOverride = nil // explicit clear
	case req.DiskLayoutOverride != nil:
		layoutOverride = req.DiskLayoutOverride // caller supplied a new override
	default:
		layoutOverride = existing.DiskLayoutOverride // preserve existing
	}

	// Resolve the power provider:
	//   - ClearPowerProvider=true → explicitly remove (revert to BMC/IPMI fallback)
	//   - PowerProvider present in request → use the new config (credentials updated)
	//   - Neither present (omitempty field absent) → preserve existing config so
	//     that a PUT to change hostname/image does not silently wipe credentials.
	var powerProvider *api.PowerProviderConfig
	switch {
	case req.ClearPowerProvider:
		powerProvider = nil // explicit clear
	case req.PowerProvider != nil:
		powerProvider = req.PowerProvider // caller supplied a new provider config
	default:
		powerProvider = existing.PowerProvider // preserve existing credentials
	}

	// S6-6: group_id column dropped. GroupID changes now route through
	// AssignNodeToGroup (which writes to node_group_memberships). An empty GroupID
	// in the request means "leave as-is". To clear, use the dedicated
	// group-membership endpoint.
	desiredGroupID := existing.GroupID
	if req.GroupID != "" {
		desiredGroupID = req.GroupID
	}

	// S2-4: accept both "tags" and deprecated "groups" from the request body.
	updReqTags := req.Tags
	if len(updReqTags) == 0 && len(req.Groups) > 0 {
		updReqTags = req.Groups
	}

	// Migration 054: resolve per-node verify timeout override.
	var verifyTimeoutOverride *int
	switch {
	case req.ClearVerifyTimeoutOverride:
		verifyTimeoutOverride = nil // revert to global
	case req.VerifyTimeoutOverride != nil:
		verifyTimeoutOverride = req.VerifyTimeoutOverride
	default:
		verifyTimeoutOverride = existing.VerifyTimeoutOverride // preserve existing
	}

	cfg := api.NodeConfig{
		ID:                    id,
		Hostname:              req.Hostname,
		HostnameAuto:          false, // admin explicitly set the hostname → mark as non-auto
		FQDN:                  req.FQDN,
		PrimaryMAC:            req.PrimaryMAC,
		Interfaces:            req.Interfaces,
		SSHKeys:               req.SSHKeys,
		KernelArgs:            req.KernelArgs,
		Tags:                  updReqTags,
		Groups:                updReqTags, // dual-emit: mirror tags into deprecated field
		CustomVars:            req.CustomVars,
		BaseImageID:           req.BaseImageID,
		PowerProvider:         powerProvider,
		GroupID:               desiredGroupID,
		DiskLayoutOverride:    layoutOverride,
		ExtraMounts:           req.ExtraMounts,
		VerifyTimeoutOverride: verifyTimeoutOverride,
		CreatedAt:             existing.CreatedAt,
		UpdatedAt:             time.Now().UTC(),
	}
	if cfg.Interfaces == nil {
		cfg.Interfaces = []api.InterfaceConfig{}
	}
	if cfg.SSHKeys == nil {
		cfg.SSHKeys = []string{}
	}
	if cfg.Tags == nil {
		cfg.Tags = []string{}
		cfg.Groups = []string{}
	}
	if cfg.CustomVars == nil {
		cfg.CustomVars = map[string]string{}
	}

	if err := h.DB.UpdateNodeConfig(r.Context(), cfg); err != nil {
		log.Error().Err(err).Msg("update node config")
		writeError(w, err)
		return
	}

	// S6-6: If the group assignment changed, propagate through node_group_memberships.
	if desiredGroupID != existing.GroupID {
		if err := h.DB.AssignNodeToGroup(r.Context(), id, desiredGroupID); err != nil {
			log.Warn().Err(err).Str("node_id", id).Str("group_id", desiredGroupID).
				Msg("update node: group assignment write failed (non-fatal)")
		} else {
			cfg.GroupID = desiredGroupID
		}
	}

	// S5-12: Record field-level config change history.
	aID, aLabel := "", ""
	if h.GetActorInfo != nil {
		aID, aLabel = h.GetActorInfo(r)
	}
	if changes, diffErr := db.DiffNodeConfigFields(sanitizeNodeConfig(existing), sanitizeNodeConfig(cfg)); diffErr == nil {
		if recErr := h.DB.RecordNodeConfigChanges(r.Context(), id, aLabel, changes); recErr != nil {
			log.Warn().Err(recErr).Str("node_id", id).Msg("update node: record config history failed (non-fatal)")
		}
	}

	if h.Audit != nil {
		h.Audit.Record(r.Context(), aID, aLabel, db.AuditActionNodeUpdate, "node", id,
			r.RemoteAddr, sanitizeNodeConfig(existing), sanitizeNodeConfig(cfg))
	}

	setNodeConfigSunsetHeader(w) // S6-7: "groups" deprecated, removed in v1.1
	writeJSON(w, http.StatusOK, cfg)
}

// DeleteNode handles DELETE /api/v1/nodes/:id
func (h *NodesHandler) DeleteNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	existing, _ := h.DB.GetNodeConfig(r.Context(), id)
	if err := h.DB.DeleteNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}
	if h.Audit != nil {
		aID, aLabel := "", ""
		if h.GetActorInfo != nil {
			aID, aLabel = h.GetActorInfo(r)
		}
		h.Audit.Record(r.Context(), aID, aLabel, db.AuditActionNodeDelete, "node", id,
			r.RemoteAddr, map[string]string{"hostname": existing.Hostname}, nil)
	}
	w.WriteHeader(http.StatusNoContent)
}

// PatchNode handles PATCH /api/v1/nodes/:id — Sprint 4 EDIT-NODE-1.
// Accepts a partial update: only fields present in the JSON body are changed.
// Fields not present are preserved from the existing record.
// Supported fields: hostname, fqdn, primary_mac, tags, kernel_args, notes, base_image_id, provider.
func (h *NodesHandler) PatchNode(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	existing, err := h.DB.GetNodeConfig(r.Context(), id)
	if err != nil {
		writeError(w, err)
		return
	}

	// Decode into a flexible map so we can tell which fields were provided.
	var patch map[string]json.RawMessage
	if err := json.NewDecoder(r.Body).Decode(&patch); err != nil {
		writeValidationError(w, "invalid JSON body")
		return
	}

	// Apply each provided field onto the existing record.
	updated := existing
	updated.UpdatedAt = time.Now().UTC()

	if v, ok := patch["hostname"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil && s != "" {
			updated.Hostname = s
		}
	}
	if v, ok := patch["fqdn"]; ok {
		var s string
		_ = json.Unmarshal(v, &s)
		updated.FQDN = s
	}
	if v, ok := patch["primary_mac"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil && s != "" {
			updated.PrimaryMAC = strings.ToLower(s)
		}
	}
	if v, ok := patch["tags"]; ok {
		var tags []string
		if err := json.Unmarshal(v, &tags); err == nil {
			if tags == nil {
				tags = []string{}
			}
			updated.Tags = tags
			updated.Groups = tags // dual-emit for backward compat
		}
	}
	if v, ok := patch["kernel_args"]; ok {
		var s string
		_ = json.Unmarshal(v, &s)
		updated.KernelArgs = s
	}
	if v, ok := patch["base_image_id"]; ok {
		var s string
		_ = json.Unmarshal(v, &s)
		updated.BaseImageID = s
	}
	if v, ok := patch["notes"]; ok {
		var s string
		_ = json.Unmarshal(v, &s)
		if updated.CustomVars == nil {
			updated.CustomVars = map[string]string{}
		}
		updated.CustomVars["notes"] = s
	}
	if v, ok := patch["provider"]; ok {
		var s string
		_ = json.Unmarshal(v, &s)
		if !api.IsValidNodeProvider(s) {
			writeValidationError(w, "provider must be one of: ipmi, proxmox, or empty string")
			return
		}
		updated.Provider = s
	}

	if err := h.DB.UpdateNodeConfig(r.Context(), updated); err != nil {
		writeError(w, err)
		return
	}

	if h.Audit != nil {
		aID, aLabel := "", ""
		if h.GetActorInfo != nil {
			aID, aLabel = h.GetActorInfo(r)
		}
		if changes, diffErr := db.DiffNodeConfigFields(sanitizeNodeConfig(existing), sanitizeNodeConfig(updated)); diffErr == nil {
			if recErr := h.DB.RecordNodeConfigChanges(r.Context(), id, aLabel, changes); recErr != nil {
				log.Warn().Err(recErr).Str("node_id", id).Msg("patch node: record config history failed (non-fatal)")
			}
		}
		// Emit a specific audit event when only the provider changed.
		auditAction := db.AuditActionNodeUpdate
		if existing.Provider != updated.Provider {
			auditAction = db.AuditActionNodeProviderChanged
		}
		h.Audit.Record(r.Context(), aID, aLabel, auditAction, "node", id,
			r.RemoteAddr, sanitizeNodeConfig(existing), sanitizeNodeConfig(updated))
	}

	setNodeConfigSunsetHeader(w)
	writeJSON(w, http.StatusOK, updated)
}

// GetNodeByMAC handles GET /api/v1/nodes/by-mac/:mac
func (h *NodesHandler) GetNodeByMAC(w http.ResponseWriter, r *http.Request) {
	mac := chi.URLParam(r, "mac")
	cfg, err := h.DB.GetNodeConfigByMAC(r.Context(), mac)
	if err != nil {
		writeError(w, err)
		return
	}
	// Pre-merge group extra mounts so the deploy client receives the full
	// effective mount list in ExtraMounts without needing a separate group lookup.
	cfg = mergeGroupExtraMounts(r.Context(), h.DB, cfg)
	setNodeConfigSunsetHeader(w) // S6-7: "groups" deprecated, removed in v1.1
	writeJSON(w, http.StatusOK, sanitizeNodeConfig(cfg))
}

// RegisterNode handles POST /api/v1/nodes/register.
// Called by the clustr client on first PXE boot. Creates a NodeConfig stub if
// the MAC is new, or updates the hardware_profile if the node already exists.
// Returns the NodeConfig and an action directive ("deploy" or "wait").
func (h *NodesHandler) RegisterNode(w http.ResponseWriter, r *http.Request) {
	const maxRegisterBodyBytes = 1 << 20 // 1 MiB
	r.Body = http.MaxBytesReader(w, r.Body, maxRegisterBodyBytes)

	var req api.RegisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		if err.Error() == "http: request body too large" {
			http.Error(w, "request body too large (max 1MB)", http.StatusRequestEntityTooLarge)
			return
		}
		writeValidationError(w, "invalid JSON body")
		return
	}

	if len(req.HardwareProfile) == 0 {
		writeValidationError(w, "hardware_profile is required")
		return
	}

	// Extract primary MAC and hostname from the hardware profile.
	primaryMAC, hwHostname := extractNodeIdentity(req.HardwareProfile)
	if primaryMAC == "" {
		writeValidationError(w, "hardware_profile must contain at least one NIC with a MAC address")
		return
	}

	// Determine the hostname for this registration pass.
	// Priority: hardware-reported hostname > auto-generated.
	// Auto-generation only applies when the hardware profile carries no hostname.
	hostname := hwHostname
	hostnameAuto := false
	if hostname == "" {
		base := autoHostname(primaryMAC)
		hostname = base
		// Resolve collisions: if the base name is taken by a different node,
		// append a numeric suffix (e.g. clustr-36e92f-2) until we find a free slot.
		for suffix := 2; ; suffix++ {
			exists, err := h.DB.HostnameExists(r.Context(), hostname)
			if err != nil {
				log.Warn().Err(err).Str("hostname", hostname).
					Msg("register node: hostname collision check failed — using base name")
				hostname = base
				break
			}
			if !exists {
				break
			}
			hostname = fmt.Sprintf("%s-%d", base, suffix)
		}
		hostnameAuto = true
		log.Info().Str("mac", primaryMAC).Str("hostname", hostname).
			Msg("register node: auto-generated hostname")
	}

	// Build FQDN for new nodes when none is reported by hardware.
	fqdn := hostname + "." + defaultDomain()

	now := time.Now().UTC()
	stub := api.NodeConfig{
		ID:               uuid.New().String(),
		Hostname:         hostname,
		HostnameAuto:     hostnameAuto,
		FQDN:             fqdn,
		PrimaryMAC:       primaryMAC,
		Interfaces:       []api.InterfaceConfig{},
		SSHKeys:          []string{},
		Tags:             []string{},
		Groups:           []string{}, // deprecated alias
		CustomVars:       map[string]string{},
		HardwareProfile:  req.HardwareProfile,
		DetectedFirmware: req.DetectedFirmware,
		CreatedAt:        now,
		UpdatedAt:        now,
	}

	// Auto-populate interfaces from hardware NICs + DHCP lease before upserting.
	// This pre-fills the Network tab for new nodes so the admin doesn't have to
	// manually enter each NIC after registration.
	autoIfaces := buildAutoInterfaces(req.HardwareProfile, h.LookupDHCPLease, h.DHCPSubnetCIDR, h.ServerIP)
	if len(autoIfaces) > 0 {
		stub.Interfaces = autoIfaces
	}

	nodeCfg, err := h.DB.UpsertNodeByMAC(r.Context(), stub)
	if err != nil {
		log.Error().Err(err).Str("mac", primaryMAC).Msg("register node: upsert failed")
		writeError(w, err)
		return
	}

	// For existing nodes that re-registered with empty interfaces, apply auto-population
	// now so the Network tab is pre-filled. We never overwrite manually-configured
	// interfaces — only fill in when the node currently has none.
	if len(nodeCfg.Interfaces) == 0 && len(autoIfaces) > 0 {
		if err := h.DB.SetNodeInterfaces(r.Context(), nodeCfg.ID, autoIfaces); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).
				Msg("register node: failed to auto-populate interfaces (non-fatal)")
		} else {
			nodeCfg.Interfaces = autoIfaces
			log.Info().Str("node_id", nodeCfg.ID).Int("count", len(autoIfaces)).
				Msg("register node: auto-populated interfaces from hardware discovery + DHCP")
		}
	}

	action := "wait"
	if nodeCfg.BaseImageID != "" {
		action = "deploy"
	}
	// A pending reimage overrides the normal wait/deploy logic: always deploy.
	// The reimage orchestrator set this flag after firing SetNextBoot(PXE) +
	// PowerCycle — the node is here because it was told to come back for a
	// fresh image.
	var dryRun bool
	if nodeCfg.ReimagePending {
		action = "deploy"
		// Look up the active reimage request to surface dry_run to the client.
		if activeReq, err := h.DB.GetActiveReimageForNode(r.Context(), nodeCfg.ID); err == nil && activeReq != nil {
			dryRun = activeReq.DryRun
		}
	}

	log.Info().Str("mac", primaryMAC).Str("hostname", nodeCfg.Hostname).
		Bool("hostname_auto", nodeCfg.HostnameAuto).
		Bool("reimage_pending", nodeCfg.ReimagePending).
		Bool("dry_run", dryRun).
		Str("action", action).Msg("node registered")

	// Pre-merge group extra mounts so the deploy client's ExtraMounts is complete.
	nodeCfg = mergeGroupExtraMounts(r.Context(), h.DB, nodeCfg)

	// Populate LDAP client config if the module is enabled. This allows the
	// deploy agent to write sssd.conf + CA into the deployed filesystem.
	if h.LDAPNodeConfig != nil && action == "deploy" {
		if ldapCfg, err := h.LDAPNodeConfig(r.Context()); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to fetch LDAP config (non-fatal)")
		} else {
			nodeCfg.LDAPConfig = ldapCfg
		}
	}

	// Populate system accounts config if any are defined. The deploy agent injects
	// these into /etc/passwd, /etc/group, and /etc/shadow during finalization.
	if h.SystemAccountsConfig != nil && action == "deploy" {
		if saCfg, err := h.SystemAccountsConfig(r.Context()); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to fetch system accounts config (non-fatal)")
		} else {
			nodeCfg.SystemAccounts = saCfg
		}
	}

	// Populate network config if the node's group has a network profile assigned.
	// The deploy agent writes NM keyfiles for bonds, VLANs, and IPoIB during finalization.
	if h.NetworkConfig != nil && action == "deploy" && nodeCfg.GroupID != "" {
		if netCfg, err := h.NetworkConfig(r.Context(), nodeCfg.GroupID); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to fetch network config (non-fatal)")
		} else {
			nodeCfg.NetworkConfig = netCfg
		}
	}

	// Populate Slurm config if the module is enabled. The deploy agent writes
	// rendered Slurm config files and enables Slurm/munge services during finalization.
	if h.SlurmNodeConfig != nil && action == "deploy" {
		if slurmCfg, err := h.SlurmNodeConfig(r.Context(), nodeCfg.ID); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to fetch Slurm config (non-fatal)")
		} else {
			nodeCfg.SlurmConfig = slurmCfg
		}
	}

	// Populate sudoers config if the feature is enabled. The deploy agent writes
	// /etc/sudoers.d/<group_cn> during finalization so LDAP group members can sudo.
	if h.SudoersNodeConfig != nil && action == "deploy" {
		if sudoersCfg, err := h.SudoersNodeConfig(r.Context()); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to fetch sudoers config (non-fatal)")
		} else {
			nodeCfg.SudoersConfig = sudoersCfg
		}
	}

	// S4-11: Merge per-deployment inject_vars from the active reimage request into
	// the node's CustomVars. inject_vars are ephemeral — they exist only in the
	// reimage_requests row and are NOT written back to node_configs, so they never
	// affect future deploys. Keys from inject_vars override matching node-level keys.
	if action == "deploy" && nodeCfg.ReimagePending {
		if injectVars, err := h.DB.GetInjectVarsForActiveReimage(r.Context(), nodeCfg.ID); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to fetch inject_vars (non-fatal)")
		} else if len(injectVars) > 0 {
			merged := make(map[string]string, len(nodeCfg.CustomVars)+len(injectVars))
			for k, v := range nodeCfg.CustomVars {
				merged[k] = v
			}
			for k, v := range injectVars {
				merged[k] = v // inject_vars win on collision
			}
			nodeCfg.CustomVars = merged
			log.Info().Str("node_id", nodeCfg.ID).Int("inject_count", len(injectVars)).
				Msg("register node: inject_vars merged into CustomVars for this deployment")
		}
	}

	// Populate ClusterHosts so the deploy agent can write /etc/hosts with all
	// cluster node IPs. Only inject on deploy actions — wait responses don't need it.
	if action == "deploy" {
		if allNodes, err := h.DB.ListNodeConfigs(r.Context(), ""); err != nil {
			log.Warn().Err(err).Str("node_id", nodeCfg.ID).Msg("register node: failed to list nodes for cluster hosts (non-fatal)")
		} else {
			var clusterHosts []api.HostEntry
			for _, n := range allNodes {
				// Only include nodes that have at least one interface with an IP.
				if len(n.Interfaces) == 0 || n.Interfaces[0].IPAddress == "" {
					continue
				}
				ip := extractIP(n.Interfaces[0].IPAddress)
				if ip == "" {
					continue
				}
				entry := api.HostEntry{
					IP:       ip,
					Hostname: n.Hostname,
				}
				if n.FQDN != "" && n.FQDN != n.Hostname {
					entry.FQDN = n.FQDN
				}
				clusterHosts = append(clusterHosts, entry)
			}
			// Add the clustr server itself so nodes can resolve "clustr" and
			// "clustr-server" without DNS. "clustr-server" is required for LDAP
			// resolution: sssd.conf contains ldap_uri = ldaps://clustr-server:636
			// (derived from os.Hostname() on the server host).
			if h.ServerIP != "" {
				domain := defaultDomain()
				clusterHosts = append(clusterHosts, api.HostEntry{
					IP:       h.ServerIP,
					Hostname: "clustr",
					FQDN:     "clustr." + domain,
					Aliases:  []string{"clustr-server"},
				})
			}
			if len(clusterHosts) > 0 {
				nodeCfg.ClusterHosts = clusterHosts
				log.Info().Int("entries", len(clusterHosts)).Str("node_id", nodeCfg.ID).
					Msg("register node: injecting cluster hosts into NodeConfig")
			}
		}
	}

	writeJSON(w, http.StatusOK, api.RegisterResponse{
		NodeConfig: &nodeCfg,
		Action:     action,
		DryRun:     dryRun,
	})
}

// DeployComplete handles POST /api/v1/nodes/:id/deploy-complete.
// Called by the clustr CLI after a successful deployment finalize.
// Sets deploy_completed_preboot_at and clears reimage_pending, transitioning the
// node to NodeStateDeployedPreboot. Subsequent PXE boots will return "exit" (disk boot).
// Also transitions any active reimage record to succeeded.
func (h *NodesHandler) DeployComplete(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Confirm node exists before updating.
	if _, err := h.DB.GetNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}

	if err := h.DB.RecordDeploySucceeded(r.Context(), id); err != nil {
		log.Error().Err(err).Str("node_id", id).Msg("deploy-complete: record succeeded")
		writeError(w, err)
		return
	}

	// Transition the active reimage record (if any) to complete.
	active, err := h.DB.GetActiveReimageForNode(r.Context(), id)
	if err != nil {
		log.Warn().Err(err).Str("node_id", id).Msg("deploy-complete: could not look up active reimage (non-fatal)")
	} else if active != nil {
		if dbErr := h.DB.UpdateReimageRequestStatus(r.Context(), active.ID, api.ReimageStatusComplete, ""); dbErr != nil {
			log.Warn().Err(dbErr).Str("reimage_id", active.ID).Msg("deploy-complete: could not update reimage record (non-fatal)")
		} else {
			log.Info().Str("reimage_id", active.ID).Str("node_id", id).Msg("deploy-complete: reimage record transitioned to complete")
			metrics.DeployTotal.WithLabelValues("complete").Inc()
		}
	}

	log.Info().Str("node_id", id).Msg("deploy-complete: node marked deployed")

	// S4-2: Fire webhook for deploy.complete.
	if h.WebhookDispatcher != nil {
		nodeForWebhook, _ := h.DB.GetNodeConfig(r.Context(), id)
		h.WebhookDispatcher.Dispatch(r.Context(), webhook.EventDeployComplete, webhook.Payload{
			NodeID:  id,
			ImageID: nodeForWebhook.BaseImageID,
		})
	}

	// Record LDAP configuration for this node if the module is enabled.
	// This locks the base DN on the first node to be configured.
	if h.RecordNodeLDAPConfigured != nil {
		// Re-read the node to get the current config hash. If the node had LDAP
		// config injected at registration time the deploy agent wrote sssd.conf; we
		// record that fact here using the node's hostname as a stable identifier.
		// The hash is computed server-side from the current LDAP config so it stays
		// in sync even if the config changed between registration and deploy-complete.
		//
		// Non-fatal: LDAP recording failure should not fail the deploy-complete response.
		if _, err := h.DB.GetNodeConfig(r.Context(), id); err == nil {
			if err := h.RecordNodeLDAPConfigured(r.Context(), id, "deploy-complete"); err != nil {
				log.Warn().Err(err).Str("node_id", id).Msg("deploy-complete: LDAP RecordNodeConfigured failed (non-fatal)")
			}
		}
	}

	w.WriteHeader(http.StatusNoContent)
}

// DeployFailed handles POST /api/v1/nodes/:id/deploy-failed.
// Called by the clustr CLI after a deployment failure.
// Sets last_deploy_failed_at, transitioning the node to NodeStateFailed.
// Does not clear reimage_pending -- admin decides whether to retry or cancel.
// Accepts an optional DeployFailedPayload body to capture exit code / phase detail.
func (h *NodesHandler) DeployFailed(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Parse optional structured payload — tolerate missing/empty body.
	var payload api.DeployFailedPayload
	if r.ContentLength != 0 {
		if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
			log.Warn().Err(err).Str("node_id", id).Msg("deploy-failed: could not parse payload (ignored)")
		}
	}

	// Confirm node exists before updating.
	if _, err := h.DB.GetNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}

	if err := h.DB.RecordDeployFailed(r.Context(), id); err != nil {
		log.Error().Err(err).Str("node_id", id).Msg("deploy-failed: record failed")
		writeError(w, err)
		return
	}

	// Transition the active reimage record (if any) to failed with exit detail.
	active, err := h.DB.GetActiveReimageForNode(r.Context(), id)
	if err != nil {
		log.Warn().Err(err).Str("node_id", id).Msg("deploy-failed: could not look up active reimage (non-fatal)")
	} else if active != nil {
		msg := payload.Message
		if msg == "" {
			msg = "deploy agent reported failure"
		}
		if dbErr := h.DB.UpdateReimageRequestFailed(r.Context(), active.ID, msg, payload.ExitCode, payload.ExitName, payload.Phase); dbErr != nil {
			log.Warn().Err(dbErr).Str("reimage_id", active.ID).Msg("deploy-failed: could not update reimage record (non-fatal)")
		} else {
			log.Info().
				Str("reimage_id", active.ID).
				Str("node_id", id).
				Int("exit_code", payload.ExitCode).
				Str("exit_name", payload.ExitName).
				Str("phase", payload.Phase).
				Msg("deploy-failed: reimage record transitioned to failed")
			metrics.DeployTotal.WithLabelValues("failed").Inc()
		}
	}

	log.Warn().
		Str("node_id", id).
		Int("exit_code", payload.ExitCode).
		Str("exit_name", payload.ExitName).
		Str("phase", payload.Phase).
		Msg("deploy-failed: node marked failed")

	// S4-2: Fire webhook for deploy.failed.
	if h.WebhookDispatcher != nil {
		nodeForWebhook, _ := h.DB.GetNodeConfig(r.Context(), id)
		h.WebhookDispatcher.Dispatch(r.Context(), webhook.EventDeployFailed, webhook.Payload{
			NodeID:  id,
			ImageID: nodeForWebhook.BaseImageID,
		})
	}

	w.WriteHeader(http.StatusNoContent)
}

// VerifyBoot handles POST /api/v1/nodes/:id/verify-boot. ADR-0008.
//
// Called by the deployed OS on first boot (via clustr-verify-boot.service systemd
// oneshot). Proves the bootloader, kernel, and systemd all started successfully.
//
// Auth: node-scoped token only. The token's bound node_id must match the URL {id}.
// Admin-scoped keys are NOT accepted here — enforced by requireNodeOwnership
// middleware in the router registration. This ensures only the node itself can
// report its own boot (the token written to /etc/clustr/node-token at finalize time
// is node-scoped and bound to that specific node's ID).
//
// State transitions:
//
//	deploy_completed_preboot_at set, deploy_verified_booted_at NULL
//	→ deploy_verified_booted_at = now()  (first call)
//	→ deploy_verified_booted_at unchanged (subsequent calls; only last_seen_at updates)
//
// Returns 204 No Content on success.
func (h *NodesHandler) VerifyBoot(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")

	// Parse the phone-home payload. Tolerate a missing body gracefully.
	var payload api.VerifyBootRequest
	if r.ContentLength != 0 {
		if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
			log.Warn().Err(err).Str("node_id", id).Msg("verify-boot: could not parse payload (ignored)")
		}
	}

	// Confirm node exists before updating.
	if _, err := h.DB.GetNodeConfig(r.Context(), id); err != nil {
		writeError(w, err)
		return
	}

	// firstTime is true only on the first phone-home for this deploy cycle
	// (deploy_verified_booted_at was NULL and is now set). Subsequent phone-homes
	// from clientd return firstTime=false so we can gate one-shot side effects.
	firstTime, err := h.DB.RecordVerifyBooted(r.Context(), id)
	if err != nil {
		log.Error().Err(err).Str("node_id", id).Msg("verify-boot: db update failed")
		writeError(w, err)
		return
	}

	log.Info().
		Str("node_id", id).
		Str("hostname", payload.Hostname).
		Str("kernel_version", payload.KernelVersion).
		Str("systemctl_state", payload.SystemctlState).
		Str("os_release", payload.OSRelease).
		Float64("uptime_seconds", payload.UptimeSeconds).
		Msgf("verify-boot: node %s (%s) verified booted: kernel=%s, systemctl=%s",
			id, payload.Hostname, payload.KernelVersion, payload.SystemctlState)

	// Flip the persistent boot order back to disk-first on the FIRST verify-boot
	// only. This is a no-op on IPMI (override was already one-shot) but is
	// critical on Proxmox where SetNextBoot wrote a persistent PXE-first config.
	// Gating on firstTime prevents the Proxmox stop+start from firing on every
	// subsequent clientd phone-home, which would cause an infinite stop/start loop.
	// Best-effort: errors are logged but do not fail the 204 response -- the node
	// is already deployed and the worst case is it PXE-boots cleanly on next cycle.
	// See docs/boot-architecture.md §10.
	if firstTime && h.FlipToDiskFirst != nil {
		if err := h.FlipToDiskFirst(r.Context(), id); err != nil {
			log.Warn().Err(err).Str("node_id", id).
				Msg("verify-boot: FlipToDiskFirst failed (non-fatal -- node is deployed; persistent boot order may still be PXE-first)")
		} else {
			log.Info().Str("node_id", id).
				Msg("verify-boot: persistent boot order flipped to disk-first")
		}
	}

	w.WriteHeader(http.StatusNoContent)
}

// buildAutoInterfaces parses the hardware profile and constructs InterfaceConfig
// entries for each non-loopback NIC with a real MAC. If LookupDHCPLease is set
// and returns a lease for the NIC's MAC, the IP/gateway are pre-filled.
// subnetCIDR is the provisioning subnet prefix length (0 defaults to 24).
// serverIP is used as the gateway when a DHCP lease is found.
func buildAutoInterfaces(hwProfile json.RawMessage, lookupLease func(mac string) net.IP, subnetCIDR int, serverIP string) []api.InterfaceConfig {
	if subnetCIDR <= 0 || subnetCIDR > 30 {
		subnetCIDR = 24
	}

	var hw struct {
		NICs []struct {
			Name string `json:"Name"`
			MAC  string `json:"MAC"`
		} `json:"NICs"`
	}
	if err := json.Unmarshal(hwProfile, &hw); err != nil || len(hw.NICs) == 0 {
		return nil
	}

	var ifaces []api.InterfaceConfig
	for _, nic := range hw.NICs {
		if nic.Name == "lo" || nic.MAC == "" || nic.MAC == "00:00:00:00:00:00" {
			continue
		}
		mac := strings.ToLower(nic.MAC)
		iface := api.InterfaceConfig{
			MACAddress: mac,
			Name:       nic.Name,
		}
		if lookupLease != nil {
			if leaseIP := lookupLease(mac); leaseIP != nil {
				iface.IPAddress = fmt.Sprintf("%s/%d", leaseIP.String(), subnetCIDR)
				if serverIP != "" {
					iface.Gateway = serverIP
				}
			}
		}
		ifaces = append(ifaces, iface)
	}
	return ifaces
}

// extractNodeIdentity parses the hardware profile JSON to find the primary MAC
// and hostname. Returns empty strings on any parse failure.
func extractNodeIdentity(profile []byte) (mac, hostname string) {
	var hw struct {
		Hostname string `json:"Hostname"`
		NICs     []struct {
			Name  string `json:"Name"`
			MAC   string `json:"MAC"`
			State string `json:"State"`
		} `json:"NICs"`
	}
	if err := json.Unmarshal(profile, &hw); err != nil {
		return "", ""
	}

	hostname = hw.Hostname

	// Pick first non-loopback NIC with a real MAC.
	for _, nic := range hw.NICs {
		if nic.Name == "lo" || nic.MAC == "" || nic.MAC == "00:00:00:00:00:00" {
			continue
		}
		return nic.MAC, hostname
	}
	return "", hostname
}

// batchNodeSpec is the per-row shape accepted by BatchCreateNodes.
type batchNodeSpec struct {
	Hostname    string            `json:"hostname"`
	FQDN        string            `json:"fqdn"`
	PrimaryMAC  string            `json:"primary_mac"`
	BaseImageID string            `json:"base_image_id"`
	Tags        []string          `json:"tags"`
	Groups      []string          `json:"groups"` // deprecated alias
	KernelArgs  string            `json:"kernel_args"`
	Interfaces  []api.InterfaceConfig `json:"interfaces"`
}

// BatchCreateNodes handles POST /api/v1/nodes/batch — BULK-1.
//
// Request body: {"nodes": [{hostname, primary_mac, base_image_id, tags, notes}, ...]}
//
// Returns per-row results: {index, status: "created"|"failed", id?, error?}.
// NOT all-or-nothing: partial success is allowed.
func (h *NodesHandler) BatchCreateNodes(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Nodes []batchNodeSpec `json:"nodes"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeValidationError(w, "invalid JSON body")
		return
	}
	if len(req.Nodes) == 0 {
		writeValidationError(w, "nodes array is empty")
		return
	}
	if len(req.Nodes) > 500 {
		writeValidationError(w, "nodes array exceeds maximum of 500 entries")
		return
	}

	type rowResult struct {
		Index  int    `json:"index"`
		Status string `json:"status"`
		ID     string `json:"id,omitempty"`
		Error  string `json:"error,omitempty"`
	}

	results := make([]rowResult, len(req.Nodes))
	ctx := r.Context()
	now := time.Now().UTC()

	actorID, actorLabel := "", ""
	if h.GetActorInfo != nil {
		actorID, actorLabel = h.GetActorInfo(r)
	}

	for i, n := range req.Nodes {
		if n.Hostname == "" {
			results[i] = rowResult{Index: i, Status: "failed", Error: "hostname is required"}
			continue
		}
		if n.PrimaryMAC == "" {
			results[i] = rowResult{Index: i, Status: "failed", Error: "primary_mac is required"}
			continue
		}
		n.PrimaryMAC = strings.ToLower(n.PrimaryMAC)

		// Normalise base_image_id: use empty string if not provided.
		if n.BaseImageID != "" {
			if _, err := h.DB.GetBaseImage(ctx, n.BaseImageID); err != nil {
				results[i] = rowResult{Index: i, Status: "failed", Error: fmt.Sprintf("base_image_id %q not found", n.BaseImageID)}
				continue
			}
		}

		tags := n.Tags
		if len(tags) == 0 && len(n.Groups) > 0 {
			tags = n.Groups
		}
		if tags == nil {
			tags = []string{}
		}

		cfg := api.NodeConfig{
			ID:          uuid.New().String(),
			Hostname:    n.Hostname,
			FQDN:        n.FQDN,
			PrimaryMAC:  n.PrimaryMAC,
			Tags:        tags,
			Groups:      tags,
			BaseImageID: n.BaseImageID,
			Interfaces:  n.Interfaces,
			KernelArgs:  n.KernelArgs,
			CustomVars:  map[string]string{},
			SSHKeys:     []string{},
			CreatedAt:   now,
			UpdatedAt:   now,
		}
		if cfg.Interfaces == nil {
			cfg.Interfaces = []api.InterfaceConfig{}
		}

		if err := h.DB.CreateNodeConfig(ctx, cfg); err != nil {
			results[i] = rowResult{Index: i, Status: "failed", Error: err.Error()}
			continue
		}

		if h.Audit != nil {
			h.Audit.Record(ctx, actorID, actorLabel, db.AuditActionNodeCreate, "node", cfg.ID,
				r.RemoteAddr, nil, map[string]string{
					"hostname": cfg.Hostname, "primary_mac": cfg.PrimaryMAC, "batch": "true",
				})
		}

		results[i] = rowResult{Index: i, Status: "created", ID: cfg.ID}
	}

	writeJSON(w, http.StatusOK, map[string]any{"results": results})
}
