package handlers

// schema_drift.go — Sprint 42 Day 3 SCHEMA-DRIFT-BANNER
//
// Detects whether the JSON Schema bundle embedded in the running binary matches
// the schemas the generate-schemas tool would produce from the current Go
// structs.  A mismatch signals that someone deployed a binary without running
// `make schemas` first, or swapped the binary without redeploying the schema
// files (which shouldn't happen in a normal release flow — the embedded FS is
// baked into the binary at compile time).
//
// Route: GET /api/v1/admin/schema-drift
// RBAC:  requireRole("admin")  (consistent with other /admin/* routes)
//
// Response shape:
//
//	{"status":"ok"|"drift","binary_hash":"...","embedded_hash":"...","mismatched_routes":[...]}
//
// The two hashes compared are:
//   - binary_hash:   SHA-256 of all schema filenames+contents as generated by
//                    the live binary's in-process reflection (what the code *would*
//                    produce if you ran make schemas right now).
//   - embedded_hash: SHA-256 of all schema filenames+contents in pkg/api.SchemaFS
//                    (what was baked into the binary at compile time).
//
// Both hashes cover the same set of files sorted deterministically so that:
//   a) hashes are reproducible across runs (no map-iteration non-determinism)
//   b) adding a new type only drifts *those* files, not everything
//
// The mismatched_routes field lists the schema filenames whose individual
// per-file SHA-256 differs — it is empty when status=ok.
//
// False-positive avoidance: the comparison is done in-process against the same
// binary, so drift is impossible in a normal single-binary release.  The only
// realistic trigger is an operator manually replacing schema files on disk (which
// is irrelevant since they're embedded) or a build system bug that produced
// divergent binaries in the same deploy.  In practice the banner should never
// fire in production.

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io/fs"
	"net/http"
	"reflect"
	"sort"
	"strings"

	"github.com/invopop/jsonschema"
	"github.com/sqoia-dev/clustr/pkg/api"
)

// SchemaDriftResponse is the JSON body returned by GET /api/v1/admin/schema-drift.
type SchemaDriftResponse struct {
	Status           string   `json:"status"`            // "ok" or "drift"
	BinaryHash       string   `json:"binary_hash"`       // SHA-256 hex of generated-in-process schemas
	EmbeddedHash     string   `json:"embedded_hash"`     // SHA-256 hex of embedded FS schemas
	MismatchedRoutes []string `json:"mismatched_routes"` // filenames whose content differs
}

// SchemaDriftHandler serves GET /api/v1/admin/schema-drift.
type SchemaDriftHandler struct{}

// Handle computes and returns the schema-drift status.
func (h *SchemaDriftHandler) Handle(w http.ResponseWriter, r *http.Request) {
	result, err := computeSchemaDrift()
	if err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		_ = json.NewEncoder(w).Encode(api.ErrorResponse{
			Error: "schema drift check failed: " + err.Error(),
			Code:  "internal_error",
		})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(result)
}

// computeSchemaDrift is the exported entry point for tests.
// It generates the expected schema content in-process (same as make schemas),
// reads the embedded FS content, and compares them file by file.
func computeSchemaDrift() (SchemaDriftResponse, error) {
	// Generate expected schemas in-process.
	generated, err := generateSchemasInProcess()
	if err != nil {
		return SchemaDriftResponse{}, fmt.Errorf("generate in-process schemas: %w", err)
	}

	// Read embedded schemas from pkg/api.SchemaFS.
	embedded, err := readEmbeddedSchemas()
	if err != nil {
		return SchemaDriftResponse{}, fmt.Errorf("read embedded schemas: %w", err)
	}

	// Compute per-file hashes and detect mismatches.
	var mismatched []string

	// Collect all filenames from both sets.
	allFiles := make(map[string]struct{})
	for k := range generated {
		allFiles[k] = struct{}{}
	}
	for k := range embedded {
		allFiles[k] = struct{}{}
	}

	// Sort for determinism.
	sortedFiles := make([]string, 0, len(allFiles))
	for k := range allFiles {
		sortedFiles = append(sortedFiles, k)
	}
	sort.Strings(sortedFiles)

	// Per-file comparison.
	for _, fname := range sortedFiles {
		genContent := generated[fname]
		embContent := embedded[fname]
		genHash := sha256.Sum256(genContent)
		embHash := sha256.Sum256(embContent)
		if genHash != embHash {
			mismatched = append(mismatched, fname)
		}
	}

	// Compute aggregate hashes (hash of sorted filename+content pairs).
	binaryHash := computeAggregateHash(sortedFiles, generated)
	embeddedHash := computeAggregateHash(sortedFiles, embedded)

	status := "ok"
	if len(mismatched) > 0 {
		status = "drift"
	}

	if mismatched == nil {
		mismatched = []string{} // never return null in JSON
	}

	return SchemaDriftResponse{
		Status:           status,
		BinaryHash:       fmt.Sprintf("sha256:%x", binaryHash),
		EmbeddedHash:     fmt.Sprintf("sha256:%x", embeddedHash),
		MismatchedRoutes: mismatched,
	}, nil
}

// computeAggregateHash returns the SHA-256 of all (filename, content) pairs in
// sorted order.  The hash is stable: same files in same order → same hash.
func computeAggregateHash(sortedFiles []string, contents map[string][]byte) [32]byte {
	h := sha256.New()
	for _, fname := range sortedFiles {
		// Separator to prevent collision between adjacent files.
		_, _ = fmt.Fprintf(h, "%s\x00", fname)
		_, _ = h.Write(contents[fname])
		_, _ = h.Write([]byte{0x01}) // record separator
	}
	var out [32]byte
	copy(out[:], h.Sum(nil))
	return out
}

// readEmbeddedSchemas reads all *.json files from pkg/api.SchemaFS schema/v1/,
// excluding openapi.json.
//
// openapi.json is an index document generated from the type schemas and is not
// itself a type schema.  Its content depends on the full buildOpenAPI() function
// in cmd/generate-schemas, which we do not replicate in-process.  Excluding it
// from the drift comparison avoids false positives while still catching the
// struct-vs-schema divergence that actually matters.
func readEmbeddedSchemas() (map[string][]byte, error) {
	result := make(map[string][]byte)
	err := fs.WalkDir(api.SchemaFS, "schema/v1", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".json") {
			return nil
		}
		// Exclude openapi.json — it is a derived index, not a type schema.
		if d.Name() == "openapi.json" {
			return nil
		}
		data, readErr := api.SchemaFS.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		result[d.Name()] = data
		return nil
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// schemaTypesForDrift is the same list as in cmd/generate-schemas/main.go.
// It must be kept in sync — any type added to the generator must also appear
// here.  The CI drift check (make schemas && git diff) is the safety net that
// catches divergence between this list and the generated files in the embed FS.
var schemaTypesForDrift = []reflect.Type{
	reflect.TypeOf(api.NodeConfig{}),
	reflect.TypeOf(api.NodeGroup{}),
	reflect.TypeOf(api.NodeGroupWithCount{}),
	reflect.TypeOf(api.BaseImage{}),
	reflect.TypeOf(api.DiskLayout{}),
	reflect.TypeOf(api.StoredDiskLayout{}),
	reflect.TypeOf(api.PartitionSpec{}),
	reflect.TypeOf(api.Bootloader{}),
	reflect.TypeOf(api.RAIDSpec{}),
	reflect.TypeOf(api.ZFSPool{}),
	reflect.TypeOf(api.FstabEntry{}),
	reflect.TypeOf(api.InterfaceConfig{}),
	reflect.TypeOf(api.BMCNodeConfig{}),
	reflect.TypeOf(api.GPGKey{}),
	reflect.TypeOf(api.Rack{}),
	reflect.TypeOf(api.NodeRackPosition{}),
	reflect.TypeOf(api.ErrorResponse{}),
	reflect.TypeOf(api.ListNodesResponse{}),
	reflect.TypeOf(api.ListImagesResponse{}),
	reflect.TypeOf(api.ListNodeGroupsResponse{}),
	reflect.TypeOf(api.ListDiskLayoutsResponse{}),
	reflect.TypeOf(api.ListRacksResponse{}),
	reflect.TypeOf(api.ListGPGKeysResponse{}),
	reflect.TypeOf(api.ListBootEntriesResponse{}),
	reflect.TypeOf(api.BootEntry{}),
	reflect.TypeOf(api.CreateBootEntryRequest{}),
	reflect.TypeOf(api.UpdateBootEntryRequest{}),
	reflect.TypeOf(api.HealthResponse{}),
	reflect.TypeOf(api.LogEntry{}),
	reflect.TypeOf(api.ListLogsResponse{}),
	reflect.TypeOf(api.RegisterRequest{}),
	reflect.TypeOf(api.RegisterResponse{}),
	reflect.TypeOf(api.ReimageRequest{}),
	reflect.TypeOf(api.CreateReimageRequest{}),
	reflect.TypeOf(api.ListReimagesResponse{}),
	reflect.TypeOf(api.NetworkProfile{}),
	reflect.TypeOf(api.BondConfig{}),
	reflect.TypeOf(api.SlurmNodeConfig{}),
	reflect.TypeOf(api.SlurmConfigFile{}),
	reflect.TypeOf(api.SlurmBuild{}),
	reflect.TypeOf(api.DHCPLease{}),
	reflect.TypeOf(api.DHCPLeasesResponse{}),
	reflect.TypeOf(api.Bundle{}),
	reflect.TypeOf(api.ListBundlesResponse{}),
	reflect.TypeOf(api.DeployProgress{}),
	reflect.TypeOf(api.BuildState{}),
	reflect.TypeOf(api.BiosProfile{}),
	reflect.TypeOf(api.NodeBiosProfile{}),
	reflect.TypeOf(api.CreateBiosProfileRequest{}),
	reflect.TypeOf(api.UpdateBiosProfileRequest{}),
	reflect.TypeOf(api.AssignBiosProfileRequest{}),
	reflect.TypeOf(api.BiosProfileResponse{}),
	reflect.TypeOf(api.ListBiosProfilesResponse{}),
	reflect.TypeOf(api.NodeBiosProfileResponse{}),
	reflect.TypeOf(api.BiosProviderVerifyResponse{}),
	reflect.TypeOf(api.InstallInstruction{}),
	reflect.TypeOf(api.AnchorPair{}),
	reflect.TypeOf(api.CreateNodeConfigRequest{}),
	reflect.TypeOf(api.CreateUserRequest{}),
	reflect.TypeOf(api.DangerousPushStageRequest{}),
	reflect.TypeOf(api.DangerousPushConfirmRequest{}),
}

// ComputeSchemaDriftForStartup is a lightweight wrapper used by server.go's
// startup goroutine.  Returns (true, nil) when drift is detected, (false, nil)
// when schemas are in sync, and (false, err) when the check itself fails.
func ComputeSchemaDriftForStartup() (bool, error) {
	result, err := computeSchemaDrift()
	if err != nil {
		return false, err
	}
	return result.Status == "drift", nil
}

// generateSchemasInProcess generates all schema files in-process using the
// same reflector config as cmd/generate-schemas/main.go.
// Returns a map of basename (e.g. "NodeConfig.json") → JSON bytes.
func generateSchemasInProcess() (map[string][]byte, error) {
	r := jsonschema.Reflector{
		AllowAdditionalProperties: false,
		DoNotReference:            false,
		RequiredFromJSONSchemaTags: true,
		Namer: func(t reflect.Type) string {
			return t.Name()
		},
	}

	result := make(map[string][]byte)
	seen := make(map[string]bool)

	for _, t := range schemaTypesForDrift {
		name := t.Name()
		if seen[name] {
			continue
		}
		seen[name] = true

		schema := r.ReflectFromType(t)
		out, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("marshal %s: %w", name, err)
		}
		result[name+".json"] = append(out, '\n')
	}

	return result, nil
}
