package supermicro

import (
	"context"
	"errors"
	"testing"

	"github.com/sqoia-dev/clustr/internal/bios"
)

// ─── parseSumINI ─────────────────────────────────────────────────────────────

func TestParseSumINI_Empty(t *testing.T) {
	got := parseSumINI("")
	if len(got) != 0 {
		t.Fatalf("got %d settings, want 0", len(got))
	}
}

func TestParseSumINI_SimpleKeyValue(t *testing.T) {
	input := `[Advanced]
Hyper-threading=Enabled
Intel Virtualization Technology=Enabled

[Boot]
Boot Mode Select=Legacy
`
	got := parseSumINI(input)
	if len(got) != 3 {
		t.Fatalf("got %d settings, want 3: %+v", len(got), got)
	}
	if got[0].Name != "Advanced.Hyper-threading" || got[0].Value != "Enabled" {
		t.Errorf("got[0] = %+v, want Name=Advanced.Hyper-threading Value=Enabled", got[0])
	}
	if got[2].Name != "Boot.Boot Mode Select" || got[2].Value != "Legacy" {
		t.Errorf("got[2] = %+v, want Name=Boot.Boot Mode Select Value=Legacy", got[2])
	}
}

func TestParseSumINI_CommentsSkipped(t *testing.T) {
	input := `# sum 2.x config
; another comment style
[Advanced]
Hyper-threading=Enabled
`
	got := parseSumINI(input)
	if len(got) != 1 {
		t.Fatalf("got %d settings, want 1: %+v", len(got), got)
	}
}

func TestParseSumINI_NoSection(t *testing.T) {
	// Keys before any section header should still be parsed (no prefix).
	input := `StandAloneKey=StandAloneValue`
	got := parseSumINI(input)
	if len(got) != 1 {
		t.Fatalf("got %d settings, want 1", len(got))
	}
	if got[0].Name != "StandAloneKey" {
		t.Errorf("Name = %q, want StandAloneKey", got[0].Name)
	}
}

func TestParseSumINI_ValueWithEquals(t *testing.T) {
	input := `[Section]
Key=value=with=equals
`
	got := parseSumINI(input)
	if len(got) != 1 {
		t.Fatalf("got %d settings, want 1", len(got))
	}
	if got[0].Value != "value=with=equals" {
		t.Errorf("Value = %q, want value=with=equals", got[0].Value)
	}
}

func TestParseSumINI_Fixture(t *testing.T) {
	// Realistic sum 2.x GetCurrentBiosCfg fixture.
	fixture := `# SUPERMICRO BIOS Configuration
# Generated by sum v2.14.0
# System: SuperServer 2029U-TRT

[Advanced]
Hyper-threading=Enabled
Intel Virtualization Technology=Enabled
SR-IOV Support=Enabled
NUMA Nodes Per Socket=1

[Boot]
Boot Mode Select=Legacy

[Security]
Secure Boot=Disabled
`
	got := parseSumINI(fixture)
	if len(got) != 6 {
		t.Fatalf("got %d settings, want 6: %+v", len(got), got)
	}

	want := map[string]string{
		"Advanced.Hyper-threading":               "Enabled",
		"Advanced.Intel Virtualization Technology": "Enabled",
		"Advanced.SR-IOV Support":                "Enabled",
		"Advanced.NUMA Nodes Per Socket":         "1",
		"Boot.Boot Mode Select":                  "Legacy",
		"Security.Secure Boot":                   "Disabled",
	}
	idx := make(map[string]string, len(got))
	for _, s := range got {
		idx[s.Name] = s.Value
	}
	for k, v := range want {
		if val := idx[k]; val != v {
			t.Errorf("%s: got %q, want %q", k, val, v)
		}
	}
}

// ─── parseSumXML ─────────────────────────────────────────────────────────────

func TestParseSumXML_Simple(t *testing.T) {
	xmlData := `<?xml version="1.0" encoding="UTF-8"?>
<BiosCfg>
  <Menu name="Advanced">
    <Setting name="Hyper-threading" selectedOption="Enabled" />
    <Setting name="Intel Virtualization Technology" selectedOption="Enabled" />
  </Menu>
  <Menu name="Boot">
    <Setting name="Boot Mode Select" selectedOption="Legacy" />
  </Menu>
</BiosCfg>`

	got, err := parseSumXML(xmlData)
	if err != nil {
		t.Fatalf("parseSumXML: %v", err)
	}
	if len(got) != 3 {
		t.Fatalf("got %d settings, want 3: %+v", len(got), got)
	}
	if got[0].Name != "Advanced.Hyper-threading" || got[0].Value != "Enabled" {
		t.Errorf("got[0] = %+v, want Name=Advanced.Hyper-threading Value=Enabled", got[0])
	}
	if got[2].Name != "Boot.Boot Mode Select" || got[2].Value != "Legacy" {
		t.Errorf("got[2] = %+v, want Name=Boot.Boot Mode Select Value=Legacy", got[2])
	}
}

func TestParseSumXML_Nested(t *testing.T) {
	xmlData := `<?xml version="1.0" encoding="UTF-8"?>
<BiosCfg>
  <Menu name="Advanced">
    <Menu name="CPU Configuration">
      <Setting name="Intel Virtualization Technology" selectedOption="Enabled" />
    </Menu>
  </Menu>
</BiosCfg>`

	got, err := parseSumXML(xmlData)
	if err != nil {
		t.Fatalf("parseSumXML: %v", err)
	}
	if len(got) != 1 {
		t.Fatalf("got %d settings, want 1: %+v", len(got), got)
	}
	want := "Advanced.CPU Configuration.Intel Virtualization Technology"
	if got[0].Name != want {
		t.Errorf("Name = %q, want %q", got[0].Name, want)
	}
}

func TestParseSumXML_Fixture(t *testing.T) {
	// Realistic sum 3.x GetCurrentBiosCfg XML fixture.
	xmlData := `<?xml version="1.0" encoding="UTF-8"?>
<BiosCfg>
  <Menu name="Advanced">
    <Setting name="Hyper-threading" selectedOption="Enabled" />
    <Setting name="SR-IOV Support" selectedOption="Enabled" />
    <Menu name="CPU Configuration">
      <Setting name="Intel Virtualization Technology" selectedOption="Enabled" />
      <Setting name="NUMA Nodes Per Socket" selectedOption="1" />
    </Menu>
  </Menu>
  <Menu name="Boot">
    <Setting name="Boot Mode Select" selectedOption="Uefi" />
  </Menu>
</BiosCfg>`

	got, err := parseSumXML(xmlData)
	if err != nil {
		t.Fatalf("parseSumXML: %v", err)
	}
	if len(got) != 5 {
		t.Fatalf("got %d settings, want 5: %+v", len(got), got)
	}

	want := map[string]string{
		"Advanced.Hyper-threading":                                    "Enabled",
		"Advanced.SR-IOV Support":                                     "Enabled",
		"Advanced.CPU Configuration.Intel Virtualization Technology":  "Enabled",
		"Advanced.CPU Configuration.NUMA Nodes Per Socket":            "1",
		"Boot.Boot Mode Select":                                       "Uefi",
	}
	idx := make(map[string]string, len(got))
	for _, s := range got {
		idx[s.Name] = s.Value
	}
	for k, v := range want {
		if val := idx[k]; val != v {
			t.Errorf("%s: got %q, want %q", k, val, v)
		}
	}
}

// ─── parseSumConfig dispatch ─────────────────────────────────────────────────

func TestParseSumConfig_DispatchINI(t *testing.T) {
	input := `[Advanced]
Hyper-threading=Enabled
`
	got, err := parseSumConfig(input)
	if err != nil {
		t.Fatalf("parseSumConfig (INI): %v", err)
	}
	if len(got) != 1 {
		t.Fatalf("got %d settings, want 1", len(got))
	}
}

func TestParseSumConfig_DispatchXML(t *testing.T) {
	input := `<?xml version="1.0" encoding="UTF-8"?>
<BiosCfg>
  <Menu name="Advanced">
    <Setting name="Hyper-threading" selectedOption="Enabled" />
  </Menu>
</BiosCfg>`
	got, err := parseSumConfig(input)
	if err != nil {
		t.Fatalf("parseSumConfig (XML): %v", err)
	}
	if len(got) != 1 {
		t.Fatalf("got %d settings, want 1", len(got))
	}
}

// ─── supermicroProvider method tests ─────────────────────────────────────────

func TestSupermicroProviderVendor(t *testing.T) {
	p := &supermicroProvider{binPath: "/nonexistent/sum"}
	if p.Vendor() != "supermicro" {
		t.Errorf("Vendor() = %q, want supermicro", p.Vendor())
	}
}

func TestSupermicroProviderBinaryMissing(t *testing.T) {
	p := &supermicroProvider{binPath: "/nonexistent/path/sum"}
	ctx := t.Context()

	_, err := p.ReadCurrent(ctx)
	if err == nil {
		t.Fatal("ReadCurrent: expected error when binary missing, got nil")
	}
	if !errors.Is(err, bios.ErrBinaryMissing) {
		t.Errorf("ReadCurrent: got %v, want to wrap ErrBinaryMissing", err)
	}

	// nil changes short-circuits before binary check — nil error expected.
	_, err = p.Apply(ctx, nil)
	if err != nil {
		t.Fatalf("Apply(nil changes): expected nil error, got %v", err)
	}

	// Non-nil changes with absent binary should return ErrBinaryMissing.
	_, err = p.Apply(ctx, []bios.Change{
		{Setting: bios.Setting{Name: "Advanced.Hyper-threading", Value: "Disabled"}, From: "Enabled", To: "Disabled"},
	})
	if err == nil {
		t.Fatal("Apply(non-nil changes) with absent binary: expected error, got nil")
	}
	if !errors.Is(err, bios.ErrBinaryMissing) {
		t.Errorf("Apply: got %v, want to wrap ErrBinaryMissing", err)
	}

	supported, err := p.SupportedSettings(ctx)
	if err != nil {
		t.Fatalf("SupportedSettings with absent binary: expected nil error (non-fatal), got %v", err)
	}
	if supported != nil {
		t.Fatalf("SupportedSettings with absent binary: expected nil slice, got %v", supported)
	}
}

// ─── Diff ────────────────────────────────────────────────────────────────────

func TestSupermicroProviderDiff(t *testing.T) {
	p := &supermicroProvider{binPath: "/nonexistent/sum"}

	current := []bios.Setting{
		{Name: "Advanced.Hyper-threading", Value: "Enabled"},
		{Name: "Boot.Boot Mode Select", Value: "Legacy"},
		{Name: "Advanced.SR-IOV Support", Value: "Disabled"},
	}
	desired := []bios.Setting{
		{Name: "Advanced.Hyper-threading", Value: "Disabled"},    // change
		{Name: "Boot.Boot Mode Select", Value: "Legacy"},         // no change
		{Name: "Advanced.Intel Virtualization Technology", Value: "Enabled"}, // new
	}

	changes, err := p.Diff(desired, current)
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	if len(changes) != 2 {
		t.Fatalf("Diff returned %d changes, want 2: %+v", len(changes), changes)
	}

	idx := make(map[string]bios.Change, len(changes))
	for _, c := range changes {
		idx[c.Name] = c
	}

	if c, ok := idx["Advanced.Hyper-threading"]; !ok {
		t.Error("expected change for Hyper-threading, not found")
	} else {
		if c.From != "Enabled" || c.To != "Disabled" {
			t.Errorf("Hyper-threading change: got From=%q To=%q, want From=Enabled To=Disabled", c.From, c.To)
		}
	}

	if c, ok := idx["Advanced.Intel Virtualization Technology"]; !ok {
		t.Error("expected change for Intel VT (new setting), not found")
	} else {
		if c.From != "" || c.To != "Enabled" {
			t.Errorf("VT change: got From=%q To=%q, want From= To=Enabled", c.From, c.To)
		}
	}
}

func TestSupermicroProviderDiffNoDrift(t *testing.T) {
	p := &supermicroProvider{binPath: "/nonexistent/sum"}

	current := []bios.Setting{
		{Name: "Advanced.Hyper-threading", Value: "Enabled"},
	}
	desired := []bios.Setting{
		{Name: "Advanced.Hyper-threading", Value: "Enabled"},
	}

	changes, err := p.Diff(desired, current)
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	if len(changes) != 0 {
		t.Errorf("Diff: got %d changes for identical settings, want 0: %+v", len(changes), changes)
	}
}
