package deploy

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/sqoia-dev/clustr/pkg/api"
)

// sles15Driver targets SUSE Linux Enterprise Server 15 (SP1 through SP6).
//
// SLES 15 diverges significantly from EL and Ubuntu:
//
//   - Network: wicked (not NetworkManager, not netplan) is the default network
//     daemon. Network config lives in /etc/sysconfig/network/ifcfg-<iface>
//     (same format as SuSEconfig / old SLES, different from EL NM keyfiles).
//     A companion /etc/sysconfig/network/ifroute-<iface> file is written for
//     default routes.
//
//   - Bootloader: grub2-install (same binary name as EL, different from
//     Ubuntu/Debian grub-install). YaST normally manages the bootloader via
//     /etc/sysconfig/bootloader and /boot/grub2/; clustr runs grub2-install
//     directly, which bypasses YaST's wrapper (yast2-bootloader). Post-deploy
//     YaST state is stale but grub2 itself boots correctly — YaST is an
//     installer concern, not a runtime concern.
//     grub2-mkconfig -o /boot/grub2/grub.cfg is used (same as EL) rather than
//     update-grub (Ubuntu/Debian).
//
//   - cloud-init: not installed by default in SLES 15 base images. AutoYaST
//     (firstboot) may be present; clustr ignores it entirely — clustr's
//     deploy is a wholesale rootfs replacement; AutoYaST is an installer tool.
//     If /etc/cloud/ is present (e.g. in a SLES public-cloud image), the
//     cloud-init disable file is written.
//
//   - DNS: /etc/resolv.conf is a plain file on SLES (wicked writes it on
//     link-up, but we write a static version for deterministic pre-boot DNS).
//
// Out of scope for v1:
//   - BTRFS snapper configuration (deploy is a full rootfs replacement).
//   - Zypper repo configuration (clustr's slurm RPM repo is EL-only in v1).
//   - AutoYaST firstboot integration.
//   - SLES for SAP (sles_sap) specific layout differences.
type sles15Driver struct{}

func init() { RegisterDriver(&sles15Driver{}) }

func (d sles15Driver) Distro() Distro { return Distro{Family: "sles", Major: 15} }

// WriteSystemFiles writes:
//  1. /etc/sysconfig/network/ifcfg-<iface>   — wicked interface config.
//  2. /etc/sysconfig/network/ifroute-<iface> — default route (when present).
//  3. /etc/resolv.conf                        — static nameserver list.
//  4. /etc/cloud/cloud.cfg.d/99-clustr-disable.cfg — only if /etc/cloud/ exists.
func (d sles15Driver) WriteSystemFiles(root string, cfg api.NodeConfig) error {
	if err := writeSLESWickedConfig(root, cfg.Interfaces); err != nil {
		return fmt.Errorf("sles15 WriteSystemFiles: wicked config: %w", err)
	}
	if err := writeSLESResolvConf(root); err != nil {
		return fmt.Errorf("sles15 WriteSystemFiles: resolv.conf: %w", err)
	}
	// cloud-init is optional on SLES public-cloud images.
	cloudDir := filepath.Join(root, "etc", "cloud")
	if _, err := os.Stat(cloudDir); err == nil {
		if err := writeUbuntuCloudInitDisable(root); err != nil {
			logger().Warn().Err(err).Msg("sles15 WriteSystemFiles: cloud-init disable (non-fatal)")
		}
	}
	return nil
}

// InstallBootloader installs GRUB2 for SLES 15.
// SLES uses grub2-install (same binary name as EL) and grub2-mkconfig
// (not update-grub).  The EFI path runs grub2-install inside a chroot.
func (d sles15Driver) InstallBootloader(ctx *bootloaderCtx) error {
	if ctx.IsEFI {
		return installSLESGRUBEFI(ctx)
	}
	if len(ctx.AllTargets) == 0 {
		return nil
	}
	return installSLESGRUBBIOS(ctx)
}

// writeSLESWickedConfig writes wicked ifcfg-* and ifroute-* files for each
// interface into /etc/sysconfig/network/.
//
// wicked ifcfg format: STARTMODE=auto, BOOTPROTO=static|dhcp,
// IPADDR=<ip/prefix>, etc.  See wicked(8) and ifcfg(5) on SLES.
func writeSLESWickedConfig(root string, ifaces []api.InterfaceConfig) error {
	netDir := filepath.Join(root, "etc", "sysconfig", "network")
	if err := os.MkdirAll(netDir, 0o755); err != nil {
		return fmt.Errorf("mkdir /etc/sysconfig/network: %w", err)
	}

	if len(ifaces) == 0 {
		// Fallback: DHCP on eth0.
		return writeSLESIfcfg(netDir, "eth0", api.InterfaceConfig{Name: "eth0"})
	}
	for _, iface := range ifaces {
		if err := writeSLESIfcfg(netDir, iface.Name, iface); err != nil {
			return err
		}
	}
	return nil
}

// writeSLESIfcfg writes a single wicked ifcfg file and, for static configs,
// an ifroute file for the default gateway.
func writeSLESIfcfg(netDir, name string, iface api.InterfaceConfig) error {
	if name == "" {
		name = "eth0"
	}

	var sb strings.Builder
	sb.WriteString("# Generated by clustr at deploy time. Do not edit manually.\n")
	sb.WriteString("STARTMODE='auto'\n")

	ip, prefix := parseIPCIDR(iface.IPAddress)
	if ip != "" {
		sb.WriteString("BOOTPROTO='static'\n")
		sb.WriteString(fmt.Sprintf("IPADDR='%s/%s'\n", ip, prefix))
		if iface.MTU > 0 {
			sb.WriteString(fmt.Sprintf("MTU='%d'\n", iface.MTU))
		}
		// Write DNS servers via NETCONFIG_DNS_STATIC_SERVERS (wicked passes
		// these to netconfig, which updates /etc/resolv.conf on link-up).
		dns := iface.DNS
		if len(dns) == 0 {
			dns = clusterDNSServers()
		}
		sb.WriteString(fmt.Sprintf("NETCONFIG_DNS_STATIC_SERVERS='%s'\n",
			strings.Join(dns, " ")))
	} else {
		sb.WriteString("BOOTPROTO='dhcp'\n")
		if iface.MTU > 0 {
			sb.WriteString(fmt.Sprintf("MTU='%d'\n", iface.MTU))
		}
	}

	ifcfgPath := filepath.Join(netDir, "ifcfg-"+name)
	if err := os.WriteFile(ifcfgPath, []byte(sb.String()), 0o600); err != nil {
		return fmt.Errorf("write ifcfg-%s: %w", name, err)
	}

	// Write the default route in ifroute-<iface> (wicked format: gateway default).
	if ip != "" && iface.Gateway != "" {
		route := fmt.Sprintf("default %s - -\n", iface.Gateway)
		routePath := filepath.Join(netDir, "ifroute-"+name)
		if err := os.WriteFile(routePath, []byte(route), 0o600); err != nil {
			return fmt.Errorf("write ifroute-%s: %w", name, err)
		}
	}

	return nil
}

// writeSLESResolvConf writes /etc/resolv.conf as a plain file.
// wicked will overwrite this on link-up via netconfig; this ensures
// the node has working DNS during the initrd and early-boot phases.
func writeSLESResolvConf(root string) error {
	etcDir := filepath.Join(root, "etc")
	if err := os.MkdirAll(etcDir, 0o755); err != nil {
		return fmt.Errorf("mkdir /etc: %w", err)
	}
	target := filepath.Join(etcDir, "resolv.conf")
	_ = os.Remove(target)

	var sb strings.Builder
	sb.WriteString("# Written by clustr at deploy time.\n")
	sb.WriteString("# wicked/netconfig will overwrite on link-up.\n")
	for _, s := range clusterDNSServers() {
		sb.WriteString("nameserver " + s + "\n")
	}
	return os.WriteFile(target, []byte(sb.String()), 0o644)
}

// installSLESGRUBBIOS runs grub2-install on all target disks for BIOS/GPT
// layouts.  SLES uses grub2-install (same as EL).
func installSLESGRUBBIOS(ctx *bootloaderCtx) error {
	log := logger()
	goCtx := context.Background()
	if ctx.Ctx != nil {
		if c, ok := ctx.Ctx.(context.Context); ok {
			goCtx = c
		}
	}

	bootDir := filepath.Join(ctx.MountRoot, "boot")
	var succeeded int
	var lastErr error

	for _, disk := range ctx.AllTargets {
		args := []string{
			"--target=i386-pc",
			"--boot-directory=" + bootDir,
			"--recheck",
		}
		if ctx.IsRAID {
			args = append(args, "--force")
		}
		if ctx.IsRAIDOnWholeDisk {
			args = append(args,
				"--skip-fs-probe",
				"--modules=mdraid1x diskfilter part_gpt btrfs xfs ext4",
			)
		}
		args = append(args, disk)

		cmd := exec.CommandContext(goCtx, "grub2-install", args...)
		if err := runAndLog(goCtx, "grub2-install", cmd); err != nil {
			lastErr = err
			log.Warn().Err(err).Str("disk", disk).
				Msg("sles15 InstallBootloader: grub2-install failed on disk")
		} else {
			succeeded++
			log.Info().Str("disk", disk).Msg("sles15 InstallBootloader: GRUB installed")
		}
	}

	if succeeded == 0 {
		return &BootloaderError{
			Targets: ctx.AllTargets,
			Cause:   lastErr,
		}
	}
	return nil
}

// installSLESGRUBEFI installs the UEFI bootloader for SLES 15 nodes.
// Required packages in the image: grub2-x86_64-efi shim.
//
// SLES note on YaST: yast2-bootloader normally manages /etc/sysconfig/bootloader
// and runs pbl (perl-Bootloader) after grub2-install.  clustr bypasses YaST
// intentionally — the deploy is a wholesale rootfs replacement and YaST's
// NVRAM/sysconfig state is irrelevant.  grub2-install --no-nvram combined with
// --removable is sufficient for UEFI removable-media boot (BOOTX64.EFI path).
func installSLESGRUBEFI(ctx *bootloaderCtx) error {
	log := logger()
	mountRoot := ctx.MountRoot
	efiDir := filepath.Join(mountRoot, "boot", "efi")

	if _, err := os.Stat(efiDir); err != nil {
		return fmt.Errorf("sles15 InstallBootloader: UEFI ESP mount point %s not accessible: %w",
			efiDir, err)
	}

	goCtx := context.Background()
	if ctx.Ctx != nil {
		if c, ok := ctx.Ctx.(context.Context); ok {
			goCtx = c
		}
	}

	if err := runGrub2InstallEFIInChrootSLES(goCtx, mountRoot); err != nil {
		return &BootloaderError{
			Targets: []string{ctx.TargetDisk},
			Cause:   fmt.Errorf("sles15 UEFI: grub2-install --target=x86_64-efi in chroot: %w", err),
		}
	}
	log.Info().Msg("sles15 InstallBootloader: grub2-install --target=x86_64-efi (chroot) succeeded")

	// SLES stores the vendor EFI binary under /boot/efi/EFI/opensuse/ (GRUB2
	// uses the opensuse bootloader-id on SLES/openSUSE for historical reasons).
	grubx64Path := filepath.Join(efiDir, "EFI", "opensuse", "grubx64.efi")
	if _, err := os.Stat(grubx64Path); err != nil {
		return &BootloaderError{
			Targets: []string{ctx.TargetDisk},
			Cause: fmt.Errorf("sles15 UEFI: grub2-install exited 0 but %s is missing — "+
				"rebuild the image with grub2-x86_64-efi and shim: %w",
				grubx64Path, err),
		}
	}
	log.Info().Str("path", grubx64Path).Msg("sles15 InstallBootloader: grubx64.efi verified")
	return nil
}

// runGrub2InstallEFIInChrootSLES runs grub2-install --target=x86_64-efi inside
// the deployed SLES 15 chroot.  SLES uses grub2-install (not grub-install)
// and grub2-mkconfig (not update-grub).
//
// bootloader-id=opensuse: SLES/openSUSE grub2 RPMs hardcode "opensuse" as the
// EFI vendor directory; using any other id leaves the vendor grub2 modules
// mismatched.  This is a SUSE-specific convention.
func runGrub2InstallEFIInChrootSLES(ctx context.Context, mountRoot string) error {
	log := logger()

	type bindMount struct{ src, dst string }
	binds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	for _, b := range binds {
		if err := os.MkdirAll(b.dst, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", b.dst, err)
		}
		if out, err := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); err != nil {
			return fmt.Errorf("bind-mount %s → %s: %w\n%s", b.src, b.dst, err, string(out))
		}
	}
	defer func() {
		for i := len(binds) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", binds[i].dst).Run()
		}
	}()

	devFD := filepath.Join(mountRoot, "dev", "fd")
	if _, err := os.Lstat(devFD); os.IsNotExist(err) {
		_ = os.Symlink("/proc/self/fd", devFD)
	}

	args := []string{
		mountRoot,
		"grub2-install",
		"--target=x86_64-efi",
		"--efi-directory=/boot/efi",
		"--boot-directory=/boot",
		"--bootloader-id=opensuse",
		"--removable",
		"--no-nvram",
		"--recheck",
		"--force",
	}
	log.Info().Strs("chroot_args", args[1:]).Msg("sles15: running grub2-install --target=x86_64-efi inside chroot")
	if err := runAndLog(ctx, "grub2-install-efi-chroot", exec.CommandContext(ctx, "chroot", args...)); err != nil {
		return fmt.Errorf("chroot grub2-install --target=x86_64-efi: %w", err)
	}

	// grub2-mkconfig regenerates /boot/grub2/grub.cfg (SLES path, not /boot/grub/).
	mkconfigArgs := []string{mountRoot, "grub2-mkconfig", "-o", "/boot/grub2/grub.cfg"}
	log.Info().Msg("sles15: running grub2-mkconfig inside chroot")
	if err := runAndLog(ctx, "grub2-mkconfig-chroot",
		exec.CommandContext(ctx, "chroot", mkconfigArgs...)); err != nil {
		// Non-fatal: the EFI shim will still boot using grub2-install's output.
		log.Warn().Err(err).Msg("sles15: grub2-mkconfig inside chroot failed (non-fatal)")
	}
	return nil
}
