package deploy

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/sqoia-dev/clustr/pkg/api"
)

// debian12Driver targets Debian 12 (Bookworm).
//
// Debian 12 diverges from Ubuntu in several ways:
//   - Network:    /etc/network/interfaces (ifupdown) is the default in Bookworm
//     base images; systemd-networkd is available but not enabled by default
//     in the standard install.  clustr writes /etc/network/interfaces.
//   - Bootloader: grub-install + update-grub (same binary names as Ubuntu).
//     Both BIOS (--target=i386-pc) and EFI (--target=x86_64-efi) paths are
//     supported; EFI runs grub-install inside a chroot.
//   - cloud-init:  often absent in standard Debian images; if the directory
//     /etc/cloud/ exists in the deployed image, clustr writes the disable file.
//   - DNS:         /etc/resolv.conf is a plain file on Debian (not a symlink to
//     systemd-resolved by default in Bookworm base images).
type debian12Driver struct{}

func init() { RegisterDriver(&debian12Driver{}) }

func (d debian12Driver) Distro() Distro { return Distro{Family: "debian", Major: 12} }

// WriteSystemFiles writes:
//  1. /etc/network/interfaces — static or DHCP ifupdown config.
//  2. /etc/resolv.conf        — nameservers for the deployed node.
//  3. /etc/cloud/cloud.cfg.d/99-clustr-disable.cfg — only if cloud-init is
//     present in the image (directory /etc/cloud/ exists).
func (d debian12Driver) WriteSystemFiles(root string, cfg api.NodeConfig) error {
	if err := writeDebianInterfaces(root, cfg.Interfaces); err != nil {
		return fmt.Errorf("debian12 WriteSystemFiles: interfaces: %w", err)
	}
	if err := writeDebianResolvConf(root); err != nil {
		return fmt.Errorf("debian12 WriteSystemFiles: resolv.conf: %w", err)
	}
	// cloud-init is optional on Debian; write the disable file only if the
	// cloud directory is present, so we do not create spurious directories in
	// non-cloud images.
	cloudDir := filepath.Join(root, "etc", "cloud")
	if _, err := os.Stat(cloudDir); err == nil {
		if err := writeUbuntuCloudInitDisable(root); err != nil {
			// Non-fatal: if cloud-init is present but we can't write the file,
			// log and continue — the node will still boot correctly.
			logger().Warn().Err(err).Msg("debian12 WriteSystemFiles: cloud-init disable (non-fatal)")
		}
	}
	return nil
}

// InstallBootloader installs GRUB2 for Debian 12.
// Debian uses the same grub-install binary as Ubuntu.
func (d debian12Driver) InstallBootloader(ctx *bootloaderCtx) error {
	if ctx.IsEFI {
		return installDebianGRUBEFI(ctx)
	}
	if len(ctx.AllTargets) == 0 {
		return nil
	}
	return installDebianGRUBBIOS(ctx)
}

// writeDebianInterfaces generates /etc/network/interfaces using the classic
// ifupdown format that Debian 12 Bookworm uses by default.
//
// Format reference: interfaces(5).
//
// When ifaces is empty, a single DHCP stanza is written for eth0 so the node
// has network access on first boot.  When interfaces are specified, each gets
// its own stanza.
func writeDebianInterfaces(root string, ifaces []api.InterfaceConfig) error {
	etcDir := filepath.Join(root, "etc")
	if err := os.MkdirAll(etcDir, 0o755); err != nil {
		return fmt.Errorf("mkdir /etc: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by clustr at deploy time. Do not edit manually.\n")
	sb.WriteString("# See interfaces(5) for documentation.\n\n")
	sb.WriteString("auto lo\n")
	sb.WriteString("iface lo inet loopback\n\n")

	if len(ifaces) == 0 {
		// Fallback: DHCP on eth0 so the node can reach the network on first boot.
		sb.WriteString("auto eth0\n")
		sb.WriteString("iface eth0 inet dhcp\n")
	} else {
		for _, iface := range ifaces {
			writeDebianIfaceStanza(&sb, iface)
		}
	}

	path := filepath.Join(etcDir, "network", "interfaces")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir /etc/network: %w", err)
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// writeDebianIfaceStanza appends a single interface stanza to sb.
func writeDebianIfaceStanza(sb *strings.Builder, iface api.InterfaceConfig) {
	name := iface.Name
	if name == "" {
		name = "eth0"
	}

	ip, prefix := parseIPCIDR(iface.IPAddress)
	if ip != "" {
		// Static configuration.
		mask := prefixLenToMask(prefix)
		sb.WriteString("auto " + name + "\n")
		sb.WriteString("iface " + name + " inet static\n")
		sb.WriteString("    address " + ip + "\n")
		sb.WriteString("    netmask " + mask + "\n")
		if iface.Gateway != "" {
			sb.WriteString("    gateway " + iface.Gateway + "\n")
		}
		dns := iface.DNS
		if len(dns) == 0 {
			dns = clusterDNSServers()
		}
		sb.WriteString("    dns-nameservers " + strings.Join(dns, " ") + "\n")
	} else {
		// DHCP.
		sb.WriteString("auto " + name + "\n")
		sb.WriteString("iface " + name + " inet dhcp\n")
	}
	sb.WriteString("\n")
}

// prefixLenToMask converts a CIDR prefix length string to a dotted-quad subnet
// mask string.  "24" → "255.255.255.0", "16" → "255.255.0.0".
// Returns "255.255.255.0" for any unrecognised input.
func prefixLenToMask(prefix string) string {
	n := parseMajorVersion(prefix) // reuse the decimal integer parser
	if n < 0 || n > 32 {
		return "255.255.255.0"
	}
	var mask uint32
	if n > 0 {
		mask = ^uint32(0) << (32 - uint(n))
	}
	return fmt.Sprintf("%d.%d.%d.%d",
		(mask>>24)&0xff,
		(mask>>16)&0xff,
		(mask>>8)&0xff,
		mask&0xff,
	)
}

// writeDebianResolvConf writes /etc/resolv.conf as a plain file.  Debian 12
// base images do not symlink resolv.conf to systemd-resolved by default, so
// we write a plain file.
func writeDebianResolvConf(root string) error {
	etcDir := filepath.Join(root, "etc")
	if err := os.MkdirAll(etcDir, 0o755); err != nil {
		return fmt.Errorf("mkdir /etc: %w", err)
	}
	// Remove any existing symlink before writing.
	target := filepath.Join(etcDir, "resolv.conf")
	_ = os.Remove(target)

	var sb strings.Builder
	sb.WriteString("# Written by clustr at deploy time.\n")
	for _, s := range clusterDNSServers() {
		sb.WriteString("nameserver " + s + "\n")
	}
	return os.WriteFile(target, []byte(sb.String()), 0o644)
}

// installDebianGRUBBIOS runs grub-install on all target disks for BIOS/GPT
// layouts.  Debian uses grub-install (same name as Ubuntu, different from EL's
// grub2-install).
func installDebianGRUBBIOS(ctx *bootloaderCtx) error {
	log := logger()
	goCtx := context.Background()
	if ctx.Ctx != nil {
		if c, ok := ctx.Ctx.(context.Context); ok {
			goCtx = c
		}
	}

	bootDir := filepath.Join(ctx.MountRoot, "boot")
	var succeeded int
	var lastErr error

	for _, disk := range ctx.AllTargets {
		args := []string{
			"--target=i386-pc",
			"--boot-directory=" + bootDir,
			"--recheck",
		}
		if ctx.IsRAID {
			args = append(args, "--force")
		}
		if ctx.IsRAIDOnWholeDisk {
			args = append(args,
				"--skip-fs-probe",
				"--modules=mdraid1x diskfilter part_gpt ext4 xfs",
			)
		}
		args = append(args, disk)

		cmd := exec.CommandContext(goCtx, "grub-install", args...)
		if err := runAndLog(goCtx, "grub-install", cmd); err != nil {
			lastErr = err
			log.Warn().Err(err).Str("disk", disk).
				Msg("debian12 InstallBootloader: grub-install failed on disk")
		} else {
			succeeded++
			log.Info().Str("disk", disk).Msg("debian12 InstallBootloader: GRUB installed")
		}
	}

	if succeeded == 0 {
		return &BootloaderError{
			Targets: ctx.AllTargets,
			Cause:   lastErr,
		}
	}
	return nil
}

// installDebianGRUBEFI installs the UEFI bootloader for Debian 12 nodes.
// Debian uses grub-install (same as Ubuntu) with --bootloader-id=debian.
// Required packages in the image: grub-efi-amd64 grub-efi-amd64-bin shim-signed.
func installDebianGRUBEFI(ctx *bootloaderCtx) error {
	log := logger()
	mountRoot := ctx.MountRoot
	efiDir := filepath.Join(mountRoot, "boot", "efi")

	if _, err := os.Stat(efiDir); err != nil {
		return fmt.Errorf("debian12 InstallBootloader: UEFI ESP mount point %s not accessible: %w",
			efiDir, err)
	}

	goCtx := context.Background()
	if ctx.Ctx != nil {
		if c, ok := ctx.Ctx.(context.Context); ok {
			goCtx = c
		}
	}

	if err := runGrubInstallEFIInChrootDebian(goCtx, mountRoot); err != nil {
		return &BootloaderError{
			Targets: []string{ctx.TargetDisk},
			Cause:   fmt.Errorf("debian12 UEFI: grub-install --target=x86_64-efi in chroot: %w", err),
		}
	}
	log.Info().Msg("debian12 InstallBootloader: grub-install --target=x86_64-efi (chroot) succeeded")

	// Verify the Debian vendor EFI binary.
	grubx64Path := filepath.Join(efiDir, "EFI", "debian", "grubx64.efi")
	if _, err := os.Stat(grubx64Path); err != nil {
		return &BootloaderError{
			Targets: []string{ctx.TargetDisk},
			Cause: fmt.Errorf("debian12 UEFI: grub-install exited 0 but %s is missing — "+
				"rebuild the image with grub-efi-amd64 and shim-signed: %w",
				grubx64Path, err),
		}
	}
	log.Info().Str("path", grubx64Path).Msg("debian12 InstallBootloader: grubx64.efi verified")
	return nil
}

// runGrubInstallEFIInChrootDebian runs grub-install --target=x86_64-efi inside
// the deployed Debian 12 chroot.  Nearly identical to the Ubuntu version but
// uses --bootloader-id=debian and update-grub.
func runGrubInstallEFIInChrootDebian(ctx context.Context, mountRoot string) error {
	log := logger()

	type bindMount struct{ src, dst string }
	binds := []bindMount{
		{"/proc", filepath.Join(mountRoot, "proc")},
		{"/sys", filepath.Join(mountRoot, "sys")},
		{"/dev", filepath.Join(mountRoot, "dev")},
		{"/dev/pts", filepath.Join(mountRoot, "dev", "pts")},
	}
	for _, b := range binds {
		if err := os.MkdirAll(b.dst, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", b.dst, err)
		}
		if out, err := exec.CommandContext(ctx, "mount", "--bind", b.src, b.dst).CombinedOutput(); err != nil {
			return fmt.Errorf("bind-mount %s → %s: %w\n%s", b.src, b.dst, err, string(out))
		}
	}
	defer func() {
		for i := len(binds) - 1; i >= 0; i-- {
			_ = exec.Command("umount", "-l", binds[i].dst).Run()
		}
	}()

	devFD := filepath.Join(mountRoot, "dev", "fd")
	if _, err := os.Lstat(devFD); os.IsNotExist(err) {
		_ = os.Symlink("/proc/self/fd", devFD)
	}

	args := []string{
		mountRoot,
		"grub-install",
		"--target=x86_64-efi",
		"--efi-directory=/boot/efi",
		"--boot-directory=/boot",
		"--bootloader-id=debian",
		"--removable",
		"--no-nvram",
		"--recheck",
		"--force",
	}
	log.Info().Strs("chroot_args", args[1:]).Msg("debian12: running grub-install --target=x86_64-efi inside chroot")
	if err := runAndLog(ctx, "grub-install-efi-chroot", exec.CommandContext(ctx, "chroot", args...)); err != nil {
		return fmt.Errorf("chroot grub-install --target=x86_64-efi: %w", err)
	}

	// update-grub regenerates /boot/grub/grub.cfg.
	log.Info().Msg("debian12: running update-grub inside chroot")
	if err := runAndLog(ctx, "update-grub-chroot",
		exec.CommandContext(ctx, "chroot", mountRoot, "update-grub")); err != nil {
		log.Warn().Err(err).Msg("debian12: update-grub inside chroot failed (non-fatal)")
	}
	return nil
}
