package deploy

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/sqoia-dev/clustr/pkg/api"
)

// ubuntu24Driver targets Ubuntu 24.04 LTS (Noble Numbat).
//
// Differences from EL:
//   - Network:    netplan YAML under /etc/netplan/ instead of NM keyfiles.
//   - Boot:       grub-install + update-grub (Ubuntu package names) instead of
//     grub2-install + grub2-mkconfig (EL package names).
//   - Cloud-init: disabled via /etc/cloud/cloud.cfg.d/99-clustr-disable.cfg
//     so cloud-init does not overwrite hostname/network on first boot.
//   - Package mgr: apt (image build only — not exercised in this file).
//
// Image capture is out of scope; this driver handles deploy-side writes only.
type ubuntu24Driver struct{}

func init() { RegisterDriver(&ubuntu24Driver{}) }

func (d *ubuntu24Driver) Distro() Distro { return Distro{Family: "ubuntu", Major: 24} }

// WriteSystemFiles writes:
//  1. /etc/cloud/cloud.cfg.d/99-clustr-disable.cfg — prevents cloud-init from
//     overwriting hostname/network on first boot.
//  2. /etc/netplan/01-clustr.yaml — static or DHCP network configuration.
func (d *ubuntu24Driver) WriteSystemFiles(root string, cfg api.NodeConfig) error {
	if err := writeUbuntuCloudInitDisable(root); err != nil {
		return fmt.Errorf("ubuntu24 WriteSystemFiles: cloud-init disable: %w", err)
	}
	if err := writeUbuntuNetplan(root, cfg.Interfaces); err != nil {
		return fmt.Errorf("ubuntu24 WriteSystemFiles: netplan: %w", err)
	}
	return nil
}

// InstallBootloader installs GRUB2 using the Ubuntu package binary names.
// Ubuntu ships grub-install (not grub2-install); the flags and semantics are
// identical to the EL path for BIOS/GPT deployments.
//
// EFI: delegated to FilesystemDeployer.Finalize which has the full partition
// table and ESP device path. Sprint 26 target: migrate EFI here.
func (d *ubuntu24Driver) InstallBootloader(ctx *bootloaderCtx) error {
	if len(ctx.AllTargets) == 0 {
		return nil
	}
	return installUbuntuGRUBBIOS(ctx)
}

// writeUbuntuCloudInitDisable writes the cloud-init override file that forces
// the null datasource, preventing cloud-init from overwriting hostname, network
// configuration, and user data on first boot. Without this, cloud-init v23+
// on Ubuntu 24.04 actively replaces files written by WriteSystemFiles.
func writeUbuntuCloudInitDisable(root string) error {
	dir := filepath.Join(root, "etc", "cloud", "cloud.cfg.d")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir cloud.cfg.d: %w", err)
	}
	content := "# Written by clustr at deploy time.\n" +
		"# Prevents cloud-init from overwriting hostname, network, and users.\n" +
		"datasource_list: [None]\n"
	path := filepath.Join(dir, "99-clustr-disable.cfg")
	return os.WriteFile(path, []byte(content), 0o644)
}

// writeUbuntuNetplan generates /etc/netplan/01-clustr.yaml for the given
// interfaces. When interfaces is empty, a wildcard DHCP stanza is written so
// the node has network access on first boot.
//
// The YAML is rendered as a string (no third-party library) because the
// structure is simple and fully deterministic.
func writeUbuntuNetplan(root string, ifaces []api.InterfaceConfig) error {
	netplanDir := filepath.Join(root, "etc", "netplan")
	if err := os.MkdirAll(netplanDir, 0o755); err != nil {
		return fmt.Errorf("mkdir netplan: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("# Generated by clustr at deploy time. Do not edit manually.\n")
	sb.WriteString("network:\n")
	sb.WriteString("  version: 2\n")
	sb.WriteString("  renderer: networkd\n")
	sb.WriteString("  ethernets:\n")

	if len(ifaces) == 0 {
		// Wildcard DHCP fallback on any en* interface (Ubuntu 24 naming convention).
		sb.WriteString("    all-en:\n")
		sb.WriteString("      match:\n")
		sb.WriteString("        name: \"en*\"\n")
		sb.WriteString("      dhcp4: true\n")
		sb.WriteString("      dhcp6: false\n")
		writeNetplanDNS(&sb, clusterDNSServers(), "      ")
	} else {
		for _, iface := range ifaces {
			writeNetplanIface(&sb, iface)
		}
	}

	path := filepath.Join(netplanDir, "01-clustr.yaml")
	// netplan reads world-readable files; 0644 is correct.
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// writeNetplanIface renders a single interface stanza into sb.
func writeNetplanIface(sb *strings.Builder, iface api.InterfaceConfig) {
	name := iface.Name
	if name == "" {
		name = iface.MACAddress
	}
	if name == "" {
		return
	}
	// YAML map key: escape colons (MAC addresses) and spaces.
	key := strings.NewReplacer(":", "_", " ", "_").Replace(name)

	sb.WriteString("    " + key + ":\n")
	if iface.MACAddress != "" {
		sb.WriteString("      match:\n")
		sb.WriteString("        macaddress: \"" + strings.ToLower(iface.MACAddress) + "\"\n")
		sb.WriteString("      set-name: \"" + key + "\"\n")
	}
	if iface.MTU > 0 {
		fmt.Fprintf(sb, "      mtu: %d\n", iface.MTU)
	}

	ip, prefix := parseIPCIDR(iface.IPAddress)
	if ip != "" {
		sb.WriteString("      dhcp4: false\n")
		sb.WriteString("      dhcp6: false\n")
		sb.WriteString("      addresses:\n")
		sb.WriteString("        - \"" + ip + "/" + prefix + "\"\n")
		if iface.Gateway != "" {
			sb.WriteString("      routes:\n")
			sb.WriteString("        - to: default\n")
			sb.WriteString("          via: \"" + iface.Gateway + "\"\n")
		}
		dns := iface.DNS
		if len(dns) == 0 {
			dns = clusterDNSServers()
		}
		writeNetplanDNS(sb, dns, "      ")
	} else {
		sb.WriteString("      dhcp4: true\n")
		sb.WriteString("      dhcp6: false\n")
		writeNetplanDNS(sb, clusterDNSServers(), "      ")
	}
}

// writeNetplanDNS appends a nameservers block to sb with the given indent.
func writeNetplanDNS(sb *strings.Builder, servers []string, indent string) {
	sb.WriteString(indent + "nameservers:\n")
	sb.WriteString(indent + "  addresses: [")
	for i, s := range servers {
		if i > 0 {
			sb.WriteString(", ")
		}
		sb.WriteString("\"" + s + "\"")
	}
	sb.WriteString("]\n")
}

// installUbuntuGRUBBIOS runs grub-install (Ubuntu package name) on all target
// disks for BIOS/GPT deployments. Mirrors installELGRUBBIOS but uses the
// Ubuntu binary name.
func installUbuntuGRUBBIOS(ctx *bootloaderCtx) error {
	log := logger()
	goCtx := context.Background()
	if ctx.Ctx != nil {
		if c, ok := ctx.Ctx.(context.Context); ok {
			goCtx = c
		}
	}

	bootDir := filepath.Join(ctx.MountRoot, "boot")
	var succeeded int
	var lastErr error

	for _, disk := range ctx.AllTargets {
		args := []string{
			"--target=i386-pc",
			"--boot-directory=" + bootDir,
			"--recheck",
		}
		if ctx.IsRAID {
			args = append(args, "--force")
		}
		if ctx.IsRAIDOnWholeDisk {
			args = append(args,
				"--skip-fs-probe",
				// Ubuntu 24 uses ext4 as the default /boot filesystem.
				"--modules=mdraid1x diskfilter part_gpt ext4 xfs",
			)
		}
		args = append(args, disk)

		cmd := exec.CommandContext(goCtx, "grub-install", args...)
		if err := runAndLog(goCtx, "grub-install", cmd); err != nil {
			lastErr = err
			log.Warn().Err(err).Str("disk", disk).
				Msg("ubuntu24 InstallBootloader: grub-install failed on disk")
		} else {
			succeeded++
			log.Info().Str("disk", disk).Msg("ubuntu24 InstallBootloader: GRUB installed")
		}
	}

	if succeeded == 0 {
		return &BootloaderError{
			Targets: ctx.AllTargets,
			Cause:   lastErr,
		}
	}
	return nil
}
